### PR TITLE
DomainContextSettings: Encode variables in lists

### PR DESCRIPTION
**Pull request by nikicc**
##### Issue

When lists of variables were stored in ContextSettings, reloading them did not work if Variables in the input data domain weren't made with `Variable.make`.

##### Description of changes
Lists in ContextSettings are also encoded/decoded as settings.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jerneju** [comment]
Please rebase.

**Comment by jerneju** [comment]
@nikicc : What is the status of this PR?

**Comment by nikicc** [comment]
I think there was some problem with this approach, but I'm not really sure. IMO the issue still persist, perhaps we should solve it differently, or just open an issue and close this PR.

**Comment by astaric** [comment]
The problem with this PR is that supporting both old style (variable stored in settings by names) and new style (variables stored as variables) is a mess. For the moment, widgets that store variables in lists should implement their own context handler that handles this.

**Pull request closed without merging**
