### PR TITLE
[FIX] Trees: Fix classification from sparse data

### PR DESCRIPTION
**Pull request by janezd**
##### Issue

Tree prediction for sparse data does not work.

##### Description of changes

Added a corresponding function in Cython.

##### Includes
- [X] Code changes
- [X] Tests

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Dela. 🌈 🥇 💫

**Comment by janezd** [comment]
Oops, this expects csr. @nikicc, it would be trivial to add a function for csc, too. Or do I just call to_csr?

**Comment by nikicc** [comment]
@janezd I would just call `to_csr`. Do you have any idea what is going on with the Mosaic test on AppVeyor?

**Comment by janezd** [comment]
I added a separate function for csr; it's almost the same, just with different indexing.

I've no idea about Mosaic. Let's see if it fails again.

**Comment by kernc** [comment]
It's tremendous satisfaction working in a team that agrees on what to optimize for.
```py
>>> import scipy.sparse
>>> csr = scipy.sparse.random(1e5, 1e4, format='csr')
>>> %timeit csr.tocsc()
417 ms ± 2.65 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by janezd** [comment]
Half a second. If the code that I added is executed ten (OK, twenty) times (on the data of this size), the time saved by adding the code will roughly equal the time I spent by adding it.

**Comment by kernc** [comment]
Thanks, that's _exactly_ what I meant. 😃

**Comment by nikicc** [comment]
Related to #2370.

**Pull request merged**
