### PR TITLE
[FIX] OWBaseLearner: Learner name is changed on output when user changes it and auto apply selected 

### PR DESCRIPTION
**Pull request by PrimozGodec**
Learner name field didn't have callback when it is changed. Problem was when user changed name and auto apply was on, because name haven't changed on output. It is fixed with this PR.

### CODE REVIEW

**Comment by lanzagar** [comment]
Now it sends a new output after every key press. This can make it really slow when connected to e.g. Test&Score.
I think in other places we apply the change on focus-out only (or when pressing enter after editing)?

**Comment by PrimozGodec** [comment]
@lanzagar I changed it that now apply happens only on focus-out. One think that I do not like too much is button that shows that field is updated but not committed. It is part of gui script. 
screenshot from 2016-07-13 13-38-22

**Comment by lanzagar** [comment]
It might be acceptable if the button appeared to the right of the text field.
Definitely not above, as in the screenshot :)

**Comment by PrimozGodec** [comment]
It has been fixed

**Comment by lanzagar** [comment]
Looks good to me now.
You can squash all commits into the first and I'll merge.

**Comment by PrimozGodec** [comment]
Done

**Pull request merged**
