### PR TITLE
Highcharts - Map contains complete functionality of heatmap, so heatmap is removed. 

### PR DESCRIPTION
**Pull request by PrimozGodec**
Due to response on highcharts/highcharts#5546 (comment) map contains complete functionality of heatmap so heatmaps is removed. It also solves the problem with duplicating the legend for ColorAxis on heatmap chart.

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@kernc may you check it?

**Comment by ajdapretnar** [comment]
Oh I so dream of having a highcharts heatmap one day instead of the one we have now. :heart:

**Comment by kernc** [comment]
Remove the JS file as well.

**Comment by PrimozGodec** [comment]
Done.

**Pull request merged**
