### PR TITLE
[FIX] Documentation fetching with redirects

### PR DESCRIPTION
**Pull request by markotoplak**
##### Issue
#3247 

##### Description of changes
Follow redirects if Qt supports it.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by astaric** [comment]
How can we test this? Which add-ons were problematic?

**Comment by astaric** [comment]
I did, and it works even when using the current master. The log says
```
Setting help to url: PyQt5.QtCore.QUrl('http://orange3-imageanalytics.readthedocs.io/en/latest/widgets/importimages.html')
```
Using PyQt 5.9.2 on mac

**Comment by markotoplak** [comment]
Does clicking on the widget and pressing F1 show the documentation?

**Comment by astaric** [comment]
Yes, it does

**Comment by astaric** [comment]
I have managed to break it on master, and after applying the fix it started working again

**Pull request merged**
