### PR TITLE
[FIX] Table names set by readers

### PR DESCRIPTION
**Pull request by lanzagar**
Although Tables should ideally be constructed using Table methods (e.g. from_file), sometimes readers are used directly (as in owfile.py). Currently names are not set properly in that case, leading to 'untitled' datasets.
This changes readers (csv,tab,excel) to return more complete data Tables with names set.

### CODE REVIEW

**Comment by astaric** [comment]
(Some) readers can work with data which is passed as a StreamIO (instead of the filename), which is used in tests to avoid writing unnecessary temp files. For those cases, name should still default to untitled (instead of crashing).

**Comment by astaric** [comment]
And some tests would be nice :)

**Comment by lanzagar** [comment]
Yuck!

```
Parameters
----------
filename : str
    name of the file to open
```
And then one subclass (without a comment) abuses the filename parameter for StringIO objects and we hack open to not open in some cases. And we want to maintain this although it is never used anywhere in the code apart from tests...?

But that should be handled in another PR / refactoring if we want this PR closed before winter :)

**Comment by kernc** [comment]
It's not uncommon for file-like objects to be supported in place of filename paths.

**Pull request merged**
