### PR TITLE
Remove unused icons form Orange/canvas/icons

### PR DESCRIPTION
**Pull request by markotoplak**
##### Includes
- [ ] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
🙌 Orange is getting come spring cleaning!

**Comment by janezd** [comment]
👍 
I was tempted to do this long ago.

Orange/canvas/icons/delete_gray.png appears in OWSetEnrichment in orange-bio. Should we check other official add-ons, too?

**Comment by astaric** [comment]
probably yes, and move the icons used to add-ons using them (possibly replacing them with svgs in the process)

**Comment by markotoplak** [comment]
orange-bio is safe. delete_gray.png is only used by a Orange 2 widget.

**Comment by markotoplak** [comment]
Add-ons text, infrared, bio, prototypes, educational, associate, timeseries, geo, network, imageanalytics do not use any of these files.

**Comment by janezd** [comment]
That's it? We can merge?

**Comment by markotoplak** [comment]
I'd say yes. Unless there any other important add-ons?

**Comment by ales-erjavec** [comment]
The svg icons are used when there is no effective style sheet overriding them (e.g. if you run `orange-canvas --stylesheet none`). They should not be removed.

**Comment by markotoplak** [comment]
@ales-erjavec , where can I find usages of these icons? Here I proposed to delete Back.svg, Get Started.svg, Maximize Toolbar.svg, Minimize Toolbar.svg which I do not find in the code.

**Comment by ales-erjavec** [comment]
> Here I proposed to delete Back.svg, Get Started.svg, Maximize Toolbar.svg, Minimize Toolbar.svg which I do not find in the code.

Sorry. I was positive the Maximize/Minimize Toolbar icons were used in the toolbar dock. But it actually uses QStyle defined icons for that.

**Pull request merged**
