### PR TITLE
Remove functions slated for removal in 3.34

### PR DESCRIPTION
**Pull request by janezd**
##### Issue

Bumping version to 3.4 triggered several time bombs. I fixed all but one.

@PrimozGodec, please check 1f2562f28d69e3e8448c20addb6052b291b0febc.
@markotoplak, please check a9b0d792780332b07d6b7cfc428009b1285d1a75 and 09deba2d03eb751bbde65d06cf03bf906432ec8d.
@JakaKokosar, @PrimozGodec or @markotoplak, please check 044a9c229fede72345966d9759c94fb70703cf9a and fix the remaining deprecation (manually adding C-Index in Test and Score).

##### Includes
- [X] Code changes

### CODE REVIEW

**Comment by PrimozGodec** [comment]
> @PrimozGodec, please check https://github.com/biolab/orange3/commit/1f2562f28d69e3e8448c20addb6052b291b0febc.

It is OK

**Comment by markotoplak** [comment]
> @markotoplak, please check [a9b0d79](https://github.com/biolab/orange3/commit/a9b0d792780332b07d6b7cfc428009b1285d1a75) and 09deba2

Looks fine. I also removed the docs and some useless imports.

**Comment by markotoplak** [comment]
> @JakaKokosar, @PrimozGodec or @markotoplak, please check [044a9c2](https://github.com/biolab/orange3/commit/044a9c229fede72345966d9759c94fb70703cf9a) and fix the remaining deprecation (manually adding C-Index in Test and Score).

I bumped that to 3.35 so that we can solve in independently of other fixes. This actually needs some thinking.

**Comment by markotoplak** [comment]
@janezd, we have a hidden Python 3.7 compatibility test: read the docs. I think @PrimozGodec is working on that, but until it is fixed, please avoid Python 3.8 syntax.

**Comment by markotoplak** [comment]
>  test: read the docs. I

readthedocs.org

**Pull request merged**
