### PR TITLE
Saving data to excel and ods

### LINKED ISSUE #3096: Save Data: allow saving to Excel format
- Enable saving to .xslx format in Save Data widget.
- Don't save with a three-row header in .csv and .xlsx, since it destroys reading these files in other libraries (e.g. pandas).

### PR DESCRIPTION
**Pull request by eadaradhiraj**
##### Issue

Fixes #3096

##### Description of changes
This pull request is to solve issue # 3096 which requests support for excel and ods file formats while saving data

##### Includes
- [X] Code changes
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
I can confirm `xlwt` and `pyexcel-ods` both install normally on Windows with pip.

**Comment by eadaradhiraj** [comment]
@kernc It seems the tests are failing, can anybody tell me how to run test_owsave.py

**Comment by eadaradhiraj** [comment]
I get this following error can anybody explain
```
  File "D:\orange3\Orange\__init__.py", line 1, in <module>
    from .misc.lazy_module import _LazyModule
  File "D:\orange3\Orange\misc\__init__.py", line 3, in <module>
    from .distmatrix import DistMatrix
  File "D:\orange3\Orange\misc\distmatrix.py", line 3, in <module>
    from Orange.data import Table, StringVariable, Domain
  File "D:\orange3\Orange\data\__init__.py", line 4, in <module>
    from .variable import *
  File "D:\orange3\Orange\data\variable.py", line 11, in <module>
    from Orange.data import _variable
ImportError: cannot import name '_variable' from 'Orange.data' (D:\orange3\Orange\data\__init__.py)
```

**Comment by ajdapretnar** [comment]
Continued in #3453.

**Pull request closed without merging**
