### PR TITLE
OWSGD: Rerrange UX

### PR DESCRIPTION
**Pull request by janezd**
##### Issue

Tests fail because the OWSGD is too high.

##### Description of changes

Rearrange the GUI into two columns + minor realignments.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by janezd** [comment]
Let somebody review and merge this (if OK), so our tests start passing again.

Screenshot 2021-01-08 at 15 29 13

**Comment by markotoplak** [comment]
There is a big margin before the last button on my Linux machine, but I am OK with it.

image

**Comment by janezd** [comment]
Is this the only widget in which this happens? I think I've seen this before, somewhere on someone's machine.

Could you please check whether removing `__init__` helps?

**Comment by markotoplak** [comment]
Removing `__init__` keeps the space on my computer. The problem is in the superclass, because also the other learners behave the same.

**Comment by markotoplak** [comment]
Actually, the problem is in the auto_apply button, because even ScatterPlot has that huge space.

**Comment by markotoplak** [comment]
Actually, the problem may be in the surrounding box. :D

**Pull request merged**
