### PR TITLE
[ENH] Heatmap: Split columns, Column annotations

### PR DESCRIPTION
**Pull request by ales-erjavec**
##### Issue

Implements gh-4661

<s>Builds on: gh-4686 which should be merged before this.</s> (was merged)

##### Description of changes

Implement split by column, and column color annotations.

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by Hrovatin** [comment]
After this PR Louvain clustering stops working. 
```

Traceback (most recent call last):
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 936, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 974, in __process_next_helper
    self.process_node(selected_node)
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 605, in process_node
    self.send_to_node(node, signals_in)
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/home/karin/Documents/git/orange3/Orange/widgets/unsupervised/owlouvainclustering.py", line 439, in set_data
    self.commit()
  File "/home/karin/Documents/git/orange3/Orange/widgets/unsupervised/owlouvainclustering.py", line 255, in commit
    k_neighbors, metric = self.k_neighbors, METRICS[self.metric_idx][1]
IndexError: list index out of range

**Comment by Hrovatin** [comment]
Except for the above, the splitting and annotation work. There is a problem with overlapping legend values (see image). The Annotation titles do not have the same font size (see image) - this seems to depend on number of rows/clusters - sometimes one annotation title is larger and in other cases the other.
Screenshot from 2020-05-15 16-08-08

Not directly related to this issue: 
When values are present in the domain but not the data they are still included in the Split by, so the annotations can look like they are shifted. Example for row splitting variable (e.g. missing C1, C20, C5,..). Could it be made more clear that some values are shown but do not have any data - maybe colored in gray or a warning message?
Screenshot from 2020-05-15 16-11-51

**Comment by ales-erjavec** [comment]
> After this PR Louvain clustering stops working.

I do not think that could be related to this.

> One of the annotation legends overlaps the heatmap.

Fixed.

> The Annotation titles do not have the same font size

Fixed.

>  There is a problem with overlapping legend values

Fixed.

**Comment by Hrovatin** [comment]
The previously pointed out bugs seem to be gone. 

The numeric/continuous variable column legend is missing a title (categorical legends for columns and rows have them). It is also positioned higher than the first row of the categorical row annotation legend, although this is only a minor problem (solely for aesthetics).

Sometimes (e.g. I selected _Zoom to fit_) the annotation titles still get small (Time, Cluster) and row group titles overlap (see image below). Interestingly, this did not happen on the transposed version. 
Screenshot from 2020-05-28 12-12-41

(Unrelated to this PR: Sometimes _Zoom to fit_ does not work immediately, so I need to first select _Zoom out_ a couple of times before selecting _Zoom to fit_ to make it work. )

I still get the Louvain clustering error - I do not get it on a master from a few days ago. It is probably not relevant for this PR.

**Comment by ales-erjavec** [comment]
I have added a title for continuous gradient legend and fixed annotation column titles size (hopefully for good).

**Comment by Hrovatin** [comment]
The fixes work as expected.

**Pull request merged**
