### PR TITLE
add images for documenation of Ariticle Scraper widget Orange3-Text

### PR DESCRIPTION
**Pull request by cheral**

### CODE REVIEW

**Comment by ajdapretnar** [comment]
@cheral We would prefer to keep the documentation for add-ons in the add-ons themselves. Orange 3 is only for core Orange. I would suggest you to make this PR to Orange3-Text and also include a written documentation ([example here](https://github.com/ajdapretnar/orange3/tree/master/doc/visual-programming/source/widgets/classify)). I'll make a PR with folders that will mirror the ones we have in Orange. You can then include you PR there. Thanks!

**Comment by cheral** [comment]
The images for preprocess text documentation are in this same orange3 folder and documentation rst file in Orange3-text. Please modify that too with your PR

**Comment by ajdapretnar** [comment]
@cheral This is Preprocess of core Orange, not Preprocess for Text Mining. From what I see, all the images in the data/images folder are correct.

**Comment by ajdapretnar** [comment]
@cheral The fix for Preprocess was merged in #1307. As of now, there are also proper folders available in the Text Mining add-on with example/template files for reference. Could you please add the documentation for Article Scraper there? Thank you!

**Pull request closed without merging**
