### PR TITLE
Fix numpy version on 1.16.*

### PR DESCRIPTION
**Pull request by PrimozGodec**
##### Issue

AppVeyor fails on openTSNE import - reason numba issue.

##### Description of changes

With this PR we fixed the numpy version on 1.1.6.* It can be undone when numba resolves an issue.

##### Includes
- [ ] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by janezd** [comment]
Seem OK. May I (change the title and) merge?

**Comment by PrimozGodec** [comment]
This PR changes just the numpy version for tests I think it is wort test if this is only the issue of AppVeyor or issue of any Windows installation. 

I mean if AppVeyor fails there is a chance that some users have a Windows machine where this will happen to.

**Comment by PrimozGodec** [comment]
I suggest fixing the numpy version for Orange until the issue is fixed.

**Comment by janezd** [comment]
Should we have ==1.6.* (as proposed in this PR) or <1.17.*? Currently it's ==1.14, and 1.14 is still OK.

**Comment by PrimozGodec** [comment]
There is also a similar issue with numpy-1.14.6 (this is what AppVeyor is currently using) 
One of the logs: https://ci.appveyor.com/project/biolab/orange3-75xll/builds/26879946?fullLog=true

**Comment by lanzagar** [comment]
OK, let's fix it to 1.16 then and hope it is soon fixed upstream and we can remove the restriction.

**Pull request merged**
