### PR TITLE
OWDataSets: Rename to Data Sets

### PR DESCRIPTION
**Pull request by irgolic**
(I seem to not know how to properly rename a widget, is there something else to do besides editing `owdatasets.py` and `widget.json`?)

I can't find a good source right now, but if I remember correctly, Data Sets is more widely agreed upon as the correct spelling of the phrase.

It'd be nice to get this in for the release, a soon-to-be-posted blog references the widget as 'Data Sets'.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
You sure you want to revisit: https://github.com/biolab/orange3/pull/2842? 😆

**Comment by irgolic** [comment]
Oh dear. Maybe we should change the blog.

**Comment by janezd** [comment]
My blog posts spell "data sets" correctly. Or they are not written. They cease to be written.

**Comment by irgolic** [comment]
I'll only change occurences of it preceding the word 'widget'.

**Pull request closed without merging**
