### PR TITLE
[CI] Add Python 3.11 to test matrices

### PR DESCRIPTION
**Pull request by ales-erjavec**
##### Issue

Add Python 3.11 to test matrices

##### Description of changes

* Add Python 3.11 to test matrices
* Skip one test on Python 3.11 due to added support for null bytes in the csv module

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by PrimozGodec** [comment]
That would solve Python 3.11 building at conda-forge https://github.com/conda-forge/orange3-feedstock/pull/122. I suggest making the 3.35.1 release after this is merged to enable conda-forge build with python 3.11

**Comment by PrimozGodec** [comment]
MacOS, Python 3.11 build fails since OpenTSNE fails to build. @pavlin-policar, do you think providing python3.11 wheels for OpenTSNE is possible?

**Comment by pavlin-policar** [comment]
Yes, definitely. I'll try to get it done asap.

**Comment by pavlin-policar** [comment]
I've just released openTSNE 1.0.0 which also adds Python 3.11. It is already available on PyPI and will probably be up on conda soon.

**Comment by PrimozGodec** [comment]
Thanks, @pavlin-policar, for making wheels and @ales-erjavec, for this PR. I just removed the unused `data` variable, which made Lint unhappy.

**Pull request merged**
