### PR TITLE
[ENH] Add appveyor configuration

### PR DESCRIPTION
**Pull request by ales-erjavec**
Add [appveyor](https://appveyor.com) CI service configuration for testing on Windows.
An example output can be [viewed here](https://ci.appveyor.com/project/ales-erjavec/orange3).

### CODE REVIEW

**Comment by ales-erjavec** [comment]
The test unfortunately take a lot of time (at least in their current state) so I do not think running on every pull request is an option.

**Comment by ales-erjavec** [comment]
Blocked on #1698

**Comment by astaric** [comment]
@ales-erjavec If the slowness of the test is the only problem, we can enable the integration, but mark it as optional. This way, appveyor builds would run, but if they take too long, we can still merge.

**Comment by ales-erjavec** [comment]
> If the slowness of the test is the only problem, we can enable the integration, but mark it as optional. This way, appveyor builds would run, but if they take too long, we can still merge.

Sure, why not.

**Comment by astaric** [comment]
The trusty build that caused the failing python3.4 tests on travis has beed disabled. Can you rebase onto the latest master so we can check if everything is in order now?

**Pull request merged**
