### PR TITLE
OWReport: fix printing to PDF on WebEngine

### PR DESCRIPTION
**Pull request by kernc**
##### Issue
Fixes https://github.com/biolab/orange3/issues/2708

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by nikicc** [comment]
This solves the issue if I click on the Save button. However, if I click on Print and then select save to PDF it still crashes with: 
```
Traceback (most recent call last):  File ".../orange3/Orange/canvas/report/owreport.py", line 357, 
in _print_report self.report_view.print_(printer)
AttributeError: 'WebviewWidget' object has no attribute 'print_'
```

Could this be fixed as well?

**Comment by astaric** [comment]
I get this:

```
Error encountered in widget Report:

Traceback (most recent call last):
  File "/Users/anze/dev/orange3/Orange/canvas/report/owreport.py", line 329, in save_report
    self.report_view.page().printToPdf(filename)
AttributeError: 'QWebEnginePage' object has no attribute 'printToPdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anze/dev/orange3/Orange/canvas/report/owreport.py", line 336, in save_report
    self.report_view.print_(printer)
AttributeError: 'WebviewWidget' object has no attribute 'print_'
```

**Comment by astaric** [comment]
This no longer crashes on Qt5.6 with webengine, but the results is not what I would expect. What gets printed is what is currently displayed in the report window, if the content is longer than the window, the image in pdf contains a scrollbar.

**Comment by astaric** [comment]
@ales-erjavec any idea how to solve it on qt 5.6?

**Comment by astaric** [comment]
As there are no obvious solutions for Qt5.6, I am merging this as-is. The printing of reports to pdf does not work for any Qt5 that uses web engine and this fix at least fixes the problem for Qt5.7+.

**Pull request merged**
