### PR TITLE
SampleData: mention oversampling in doc

### PR DESCRIPTION
**Pull request by astaric**
##### Description of changes
Add an oversampling example into SampleData widget docs.

##### Includes
- [ ] Code changes
- [ ] Tests
- [X] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
I would prefer to do it the standard way, with the entire workflow included. I am already working on this PR as some other things need to be updated in the docs, too.

**Comment by ajdapretnar** [comment]
Let me know if I should continue with my PR or you will merge this one.

**Comment by astaric** [comment]
If you have already started working on this, we can close this one.

**Comment by ajdapretnar** [comment]
Closed in favour of #3245.

**Pull request closed without merging**
