### PR TITLE
[FIX] table_to_frame: metas lost on conversion

### PR DESCRIPTION
**Pull request by itslarin**
##### Includes
- [X] Code changes
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by VesnaT** [comment]
Thank you for the PR.

Some comments:
- Have you thought of adding an argument to the `table_to_frame` i. e. `include_metas=False ` to ensure backward compatibility?
- Some unittests would be nice.

**Comment by itslarin** [comment]
Hi, Vesna.

>>Have you thought of adding an argument to the table_to_frame i. e. include_metas=False to ensure backward compatibility?

In my personal opinion this parameter can cause confusion in further usage, i believe by default table supposed to be transformed into frame without any columns lost. The user always can drop some columns explicitly if he needs. There might be some incompatibility though in case somebody rely on output frame columns number (maybe in tests). Otherwise i guess additional (in comparison with prev. results) datarfame columns shouldnt provide any harm to existing code.

**Comment by VesnaT** [comment]
All that is true and I agree with you, but still, the existing code should not be broken. 
Nobody knows how many add-ons are using the function, all expecting dataframes without metas. 
If you don't like the additional parameter, you can add it temporarily and raise a deprecation warning, to allow users to fix their code. The parameter can be removed in the next version.

**Comment by janezd** [comment]
> ...  in the next version

Or a year. Better.

**Comment by janezd** [comment]
Decision at the meeting: @VesnaT implements what she proposed here and merges the PR.

**Pull request merged**
