### PR TITLE
[FIX] Ensure unique var names in file

### PR DESCRIPTION
**Pull request by AndrejaKovacic**
##### Issue

Fixes part of  #4382
File widget allowed renaming vars with no regards for possible duplicates it may create.

##### Description of changes
As in other widgets, duplicates are checked by get_unique_name_duplicates and a warning is shown.

##### Includes
- [X] Code changes
- [X] Tests

### CODE REVIEW

**Comment by janezd** [comment]
This changes the user input -- and the change, at least on my Qt, isn't visible until I click Apply and then click one of variables.

I would change it so that the user either wouldn't be allowed to use the name that already exists (this would be a typical solution when renaming files) or I would keep the names set by the user as they are, and only rename the output variables, in the background (this is what most widgets do).

I am more inclined towards the latter. We will need this same thing in many other widgets, so perhaps it would make sense to write a function `Orange.data.util.create_safe_domain(attributes, class_vars, variables)` (name is up to discussion) that would get "proposed" names of attributes, class_vars and variables, rename them as needed and return a tuple `(domain, renamed_variables)`.

**Comment by janezd** [comment]
@AndrejaKovacic, I'm so sorry that I did it again. :( After I realized my above comment makes no sense, I started poking around and changed the code here and there to see how this should be done ... and ... then it felt stupid to throw the changes away. I promise to discipline myself in the future.

You changed the code in the right place I think, but there were two problems. One is that it modifies the user's modifications, as I complained above. The other is that `DomainEditor.get_domain` used an attribute (`renamed_variables`) to return result. That is, `renamed_variables` is not a property of the object but just an information that is stored there to be retrieved after calling `get_domain`.

I changed your code so that it returns renamed variables as a part of result and so that it renames variables without changing the model.

**Comment by AndrejaKovacic** [comment]
To break the current iteration, rename the attributes to:
iris (1) (1)
iris (1)
iris (1)
iris 
iris

**Comment by janezd** [comment]
This time, the problem was that I didn't escape a regular expression, so it didn't properly parse names that included parentheses. It would be even more interesting if you named a variable `"unclosed parentheses("`.

**Pull request merged**
