### PR TITLE
Revert "WebEngineView: delay showing the widget a bit"

### PR DESCRIPTION
**Pull request by kernc**
This reverts commit 6f7c4392b23374ebde88ade62a9457dd5972d30f.

##### Issue
Fixes https://github.com/biolab/orange3-prototypes/issues/113

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by astaric** [comment]
Why? Did it break something or it just did not fix the problem?

**Comment by kernc** [comment]
It's obviously _wrong_. It's not necessary one wishes to _show_ the QWidget immediately when _constructing_ it? The issue didn't appear elsewhere for some reason, but resulted in webview window [popped open with 1ka widget](https://github.com/biolab/orange3-prototypes/issues/113). It does help with redrawing, though, to delay showing the widget after WebEngine had had some time to load; just not like 6f7c439.

**Comment by astaric** [comment]
Thanks for the explanation. I guess this should make it to 3.9. @lanzagar, please remove from the milestone if you think otherwise.

PS. Does anyone know when is the feature freeze for 3.9?

**Comment by lanzagar** [comment]
Although I cannot reproduce the referenced issue, I think we can include this in 3.9 (@ajdapretnar can you confirm this solves the window popup).
Otherwise I think feature freeze for 3.9 was last Friday? :) We should process the 7 open PRs and release soon.

**Comment by ajdapretnar** [comment]
@lanzagar The mysterious window is gone with the revert.

**Pull request merged**
