### PR TITLE
[WIP] DataHashContextHandler

### PR DESCRIPTION
**Pull request by jerneju**
##### Issue
See 
- https://github.com/biolab/orange3/pull/2301#discussion_r118804152
- https://github.com/biolab/orange3/pull/2301#issuecomment-304228325

##### Description of changes
Work in progress.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by janezd** [comment]
@astaric, what did we decide about data hash context handlers? Do I recall correctly that you argued against them?

**Comment by astaric** [comment]
I have argued that they do not make sense for storing selections, as selections are not really context settings. (you usually do no want to restore the selection when a new widget instance sees the data it has seen before) For those cases, schema-only settings make more sense.

I someone knows of another case where DataHashContextHandler would be useful, I can argue against that as well :)

**Comment by janezd** [comment]
Do we merge things we don't (yet?) need? Or do we close the PR and hope we remember it in case we eventually need it?

**Comment by astaric** [comment]
I vote for closing.

**Comment by kernc** [comment]
> Do we merge things we don't (yet?) need?

Never a question. [YAGNI](http://wiki.c2.com/?YouArentGonnaNeedIt).

**Pull request closed without merging**
