### PR TITLE
[WIP] Model based imputer 2

### PR DESCRIPTION
**Pull request by mstrazar**
Extended model-based imputation to multiple Learners.
- User can specify separate learners for continuous and discrete variables. If not specified, models default to Mean Learner (average / most frequent value). 
- Models now impute only unknown values and not the whole column.
- Fixed a bug for Model based and Random imputation where the *data on input* was overriden by imputation results.

### CODE REVIEW

**Comment by lanzagar** [comment]
Methods for imputing have been moved from the widget to their correct place in the Orange library.
Can you check the state of model imputation there and make sure it can be used in scripts as well as in the widget. This will probably require some refactoring of your changes.

**Comment by lanzagar** [comment]
Also, there are some print calls in the code - they should be avoided. Widgets should show appropriate warnings in the GUI and library calls should generally be silent.

**Comment by kernc** [comment]
And while at it, please put replacement of `numpy` with `np` into a separate commit. You can fix this with:
```bash
git reset HEAD^^  # revert the two commits, obtain changes unstaged and in-tact
git fetch upstream master   # update the biolab's master here called upstream by convention*
git rebase --autostash -i upstream/master  # rebase your branch on this master; resolve conflicts
git add -p  # selectively add changes to a changeset
git commit  # commit this changeset
# repeat git add -p ...
```
* https://help.github.com/articles/syncing-a-fork/

**Comment by janezd** [comment]
@mstrazar Check whether this is still needed or obsolete.

**Comment by lanzagar** [comment]
As discussed things have changed so much that it would make more sense to prepare a new pull request.

**Pull request closed without merging**
