### PR TITLE
[FIX] OWMap: minor fixes

### PR DESCRIPTION
**Pull request by kernc**
##### Issue
Geo Map crashed when data input, then subset input, then data input cleared.
Geo Map showed warning when setting DomainModel-controlled master value attributes to None.

##### Description of changes
Neither of above should happen.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by kernc** [comment]
https://sentry.io/biolab/orange3/issues/282989002/

**Comment by ajdapretnar** [comment]
This works for the workflow we talked about. However, the widget crashes when I connect it to a data set without any numerical features (say, bookexcerpts.tab), open GeoMap and press 'zoom in' function. Also it is constantly printing out all the tokens from the 'Unable to set ComboBox' error. Perhaps just something to keep the console clean?
The rest is good.

**Comment by kernc** [comment]
Thanks. Please see again.

**Comment by ajdapretnar** [comment]
This is good! I like the changes.

But again, what to do regarding the checks?

**Pull request merged**
