### PR TITLE
[FIX] File: Disallow changing string columns to datetime

### PR DESCRIPTION
**Pull request by jerneju**
##### Issue
ValueError  - could not convert string to float: '02.02.17'
https://sentry.io/biolab/orange3/issues/196743724/

##### Description of changes
Datetime option only if numerical.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/198615964/

**Comment by jerneju** [comment]
#1520, #1798

**Comment by ajdapretnar** [comment]
This fixes the error nicely, but I was wondering whether we could provide the user with a better error message. Perhaps "Use ISO format for datetime variables (e.g. 2017-02-27)"? Say in a form of a warning? Just to tell the user how to proceed with datetime variables? :)

**Comment by jerneju** [comment]
ISO 8601? Yes, program knows how to read "2017-03-01" but have no clue what means "2017-03-01T12:49:39+00:00" ("could not convert string to float").

**Comment by ajdapretnar** [comment]
Complain to @kernc. It does work with _2017-03-01 12:49:39_ though.
Can we come up with a good user message?

**Comment by jerneju** [comment]
Great, I see it does work with that kind of format. I changed the code in a way that a user message won't be necessary. Now only variables which can be set to numerical can also be set to datetime.

**Comment by astaric** [comment]
Could you include a test?

**Comment by kernc** [comment]
From the top of the head, the reason it didn't work with:

> 2017-03-01T12:49:39+00:00

is that the colon in the timezone part doesn't parse with [`datetime.strptime`](http://strftime.org/). Standards-wise, I guess we deviate a little.

**Pull request merged**
