### PR TITLE
[FIX] Settings: check for attributes before comparing

### PR DESCRIPTION
**Pull request by jerneju**
##### Issue
https://sentry.io/biolab/orange3/issues/256593225/

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/256593225/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/242062399/

**Comment by astaric** [comment]
Why would there be a context that does not have attributes?

**Comment by astaric** [comment]
Context handlers should be allowed to assume that the context is of the correct kind. The right way to approach this should be fixing the offending widget, which is (although at the moment incorrectly) being done in #2254. Let's continue the discussion there.

**Pull request closed without merging**
