### PR TITLE
[FIX] Add-ons: Handling ValueError due to connection problems

### PR DESCRIPTION
**Pull request by jerneju**
##### Issue
https://sentry.io/biolab/orange3/issues/252756389/

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/252756389/

**Comment by jerneju** [comment]
Should user be informed about this error via dialog?

**Comment by ajdapretnar** [comment]
Yes. I'd go for a warning - Cannot connect to the internet. Please try again.
Or something similar, but not too long. :)

**Comment by jerneju** [comment]
Fixed.

**Pull request merged**
