### PR TITLE
Revert "[REF] Rename Data Sets to Datasets"

### PR DESCRIPTION
**Pull request by janezd**
Reverts biolab/orange3#2842.

There seems no consensus in the community, with native speakers leaning towards "data sets". We thus don't gain anything by changing this, except for outdating screenshot, manuals, tutorials...

We currently consistently write it separately in all materials we publish, so let's keep it this way.

### CODE REVIEW

**Comment by kernc** [comment]
_Almost_ consistently. But there is no pain in it. Natural languages are alive and common pairs of noun words have a tendency to, sometimes, first get hyphenated, then merged. Let's wait another decade or so.

**Comment by jerneju** [comment]
Kaggle uses _datasets_: https://www.kaggle.com/datasets .

**Comment by jerneju** [comment]
**Google** uses _datasets_: https://cloud.google.com/public-datasets/ .
**Amazon** uses _datasets_: https://aws.amazon.com/public-datasets/ .

**Comment by janezd** [comment]
Sure does, yes. Consistently. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-public-data-sets.html

Would never ever write it separately on this page: https://cloud.google.com/bigquery/public-data/

Would somebody please fix the Wikipedia page. It's all wrong! Outdated. https://en.wikipedia.org/wiki/Data_set. SAD!

My point is exactly that you can write it like this or like that, thanks. If both are right, there is totally no reason to make Orange inconsistent with itself and all existing materials we have. 

Let me answer what @astaric will now most surely remark now (so he does not have to bother doing it). This renaming makes no sense, it does not achieve anything, except for presumably following the presumed trend. In this respect this is not the same as renaming discrete to categorical and continuous to numeric: I asked my wife. She had no clue about discrete (and confused it with discreet because we talked in Slovene where the word is the same), and continuous variable is a variable that is measure regularly. So: she missed, both term. When asked about numerical and categoric, she described the former as "numbers" and the latter as, say, gender. Correct, both. Continuous and discrete made no sense for most people, and numeric and categorical do, for most people. This is why renaming variable types made sense, although it introduced inconsistence. Renaming data sets does not serve any purpose. Period.

I had a senate meeting on Tuesday. Wasted three hours repeating the same thing for the n-th time (for the m-th month in a row). Left totally pissed; told the dean to finish the session or I'm leaving. And perhaps never coming back.

I'm not wasting any more time on this, either.

**Pull request closed without merging**
