### PR TITLE
Rearrange a few widgets' UX to decrease their heights

### PR DESCRIPTION
**Pull request by janezd**
##### Issue

Fixes (partially) #4608.

##### Description of changes

I changed the widgets roughly along the lines we set we discussing the issue, except for making ROC scrollable. If the user wants smaller graphs, (s)he can hide the control area, like in other widgets, IMHO.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
- Pivot: both Auto Apply and top box have extra space that doesn't have to be there. Something like `box_label=False`?
- Statistics: I would prefer having the numbers aligned. 😇 Also, try hiding and showing controlArea. The widget behaves in a strange way. How about doing in Continuize style, with stats below each corresponding window? Do stats have to be mainArea?
- Impute: Apply automatically probably doesn't need this super extended box?

Otherwise, I have to say some solutions are quite elegant. I like Continuize. At first it looks strange, but then I started liking it more and more.

**Comment by ajdapretnar** [comment]
Examples of changes for future reference:

**Pivot**
Screen Shot 2020-05-08 at 10 49 32

**ROC Analysis**
Screen Shot 2020-05-08 at 11 10 37

**Continuize**
Screen Shot 2020-05-08 at 11 10 13

**Purge Domain**
Screen Shot 2020-05-08 at 11 11 47

**Impute**
Screen Shot 2020-05-08 at 11 10 16

**Comment by markotoplak** [comment]
I like the changes.

Another minor issue: Impute should also have margins fixed. Margins around the upper two boxes are much bigger than in any other widget. That was already there before the PR.

**Comment by markotoplak** [comment]
Also, in Purge domain the top left and right boxes not valigned.

**Comment by janezd** [comment]
Uh, this looks horrible, as if they are too large and space is inserted everywhere. See my screenshots below.

Impute's margins on my machine are perhaps even too small, and the top two boxes in Purge are aligned.

I suspected it was saved geometry, but I saved a schema with an old master and reloaded it, and they look OK.

I can't debug this. Could you try, please?

purge
pivot
impute

**Comment by ajdapretnar** [comment]
I think it could be an issue with my settings. I am getting strange fonts and extra spaces everywhere for some reason. I noticed my old screenshots did not have this. 🤷

**Comment by markotoplak** [comment]
I see the same things as @janezd. @lanzagar, can you check on Linux?

**Comment by lanzagar** [comment]
I get the same extra spaces and misalignments as @ajdapretnar !

**Comment by markotoplak** [comment]
@lanzagar, and what happens in master?

**Comment by lanzagar** [comment]
Well Purge Domain for example does not have two columns on master so there is no alignment there, while here Features and Statistics boxes are not aligned for me like they are for @janezd (see @ajdapretnar's screenshot).
The empty space at the top of the new Pivot gui is also not there on master, because the box on master has a title, while here it is an untitled box with labels inside. But otherwise this is not this PR's fault - untitled boxes have empty space on top on master and here (not sure when this started happening, maybe it has to do with the qt version?).
The above also applies to auto commit boxes - the extra space is because they are in untitled boxes.

**Comment by janezd** [comment]
So, is there something we can fix here? If so, can you try to fix it -- I can't because it works for me...

**Comment by ajdapretnar** [comment]
I think we saw something similar if Timeseries four weeks ago. I cannot remember the exact fix, it was something like `box_label = False`. Perhaps @robertcv, @irgolic or @AndrejaKovacic remember what it was?

**Pull request merged**
