### PR TITLE
README: Update README shields

### PR DESCRIPTION
**Pull request by irgolic**
Fixes the failing build one (still linked to Travis)
Adjusts style, colors

Should we add any other badges?
Shields.io supports:
- PyPi download count

- latest version

- supported platforms

- open issue count

... many more

You can also connect it to your own endpoint, we could potentially set up an endpoint for download count, merging the numbers we get on our website with the ones on PyPi (and the ones on conda?).

### CODE REVIEW

**Comment by pavlin-policar** [comment]
We don't support win-32. I wouldn't have too many badges, it looks really spammy and it's easy to go overboard. The version badge IMO is pointless, because is easy to see on the GH page, where it shows the latest tag. The license badge would be nice to have, so it's obvious how it's licensed without having to go into the actual LICENSE file.

**Comment by ajdapretnar** [comment]
PyPi download count is not really informative for the user, IMHO.
Neither is open issue count.
Version I don't mind, but one can indeed easily spot it.

Also in favour of not having too many. Just relevant (informative) ones.

**Comment by irgolic** [comment]
> We don't support win-32.
Conda apparently thinks we do.

Keep in mind, when a non-GitHub-savvy user sees our page, their eyes focus in on the README, if we're lucky. That's why it's nice to have the information we deem relevant there, even if it leads to redundancy.

I'd love to include a shields for all the docs we have (throughout the README), but that'll have to be part of a bigger README redesign.

**Comment by pavlin-policar** [comment]
> Conda apparently thinks we do.

conda-forge is the reason we don't. They were the ones who dropped support in 2019 Q2: https://github.com/conda-forge/staged-recipes/issues/5640, https://github.com/biolab/orange3/issues/3939. We just followed suit.

**Comment by irgolic** [comment]
https://anaconda.org/conda-forge/orange3

Ah, technically we support it with v3.13.0.

**Comment by markotoplak** [comment]
For me, the relevant ones are the latest version, perhaps a link to docs or to chat, and a download link to our webpage - only those, as someone wrote up there, that would help users. 

I would actually remove ones meant for the developers (test status, coverage).

**Comment by irgolic** [comment]
> I would actually remove ones meant for the developers (test status, coverage).

I'm inclined to agree, and I'm not really sure why most repositories show test status and coverage at the top of their READMEs. I suppose it imbues the user with some confidence in your product if you have good coverage and your build is passing? I'd think most non-developers wouldn't even think to question it.

Then again, GitHub is somewhat a social network for developers. But since we use GitHub as our issue tracker, our README must target both non-tech-savvy (our primary target userbase) and developer audiences.

Currently, our development workflow and documentation are very well hidden from sight, I myself didn't know about most of it up until recently. This makes it hard for anyone outside the Biolab bubble to join as a developer, even though we're an open-source project.

Right now, from what I can tell, in support of extending the community, we provide good first issue tags, and a CONTRIBUTING.md file. The latter is only relevant when a user first attempts to make a contribution, they're shown it as such:
screenshot

I have a lot of good first issues noted down, but if I were to post them all on the issues page, it would be flooded. I suppose if we were to change our workflow to accommodate attracting more external contributors, we would switch to a GitHub board for meetings.

The first thing anyone looks at when their interest is piqued is our README. I'm thinking of restructuring it as follows, interspersed with text, of course:

Intro (aimed at laymen)
- A bigger image, such as the one on the main page
- Version, Download, Orange Visual Programming docs, Chat shields. I'd love to include a downloads shield here too for clout, but not just PyPi numbers.
- A screenshot of Orange GUI

Contributing (aimed at developers)
- Build, coverage shields (+ # of contributors shield, commits/month shield?). The purpose of these shields is to tell people that the project is well, alive, and active
- Explanation of orange3, canvas-core, widget-base (i.e., if you want to contribute UX/UI improvements, look at canvas-core)
- Development docs shield + link to contribution guidelines
- "Good first issue" issues shield
- Invite to join Discord (chat shield, again)
- Step by step guide on setting up Orange in development (making sure `pip install -e .`/`python setup.py develop` is clearly conveyed)

Installation
- Download shield (again)
- (as is, but should this deviate as much as it does from Orange's download page?)

Another (somewhat related) thing, we should look into committing PyCharm run/debug configurations, it'll be easier for people to get started on Orange with an IDE.

**Pull request merged**
