### PR TITLE
Introduce sizeHints for Scatter Plot

### PR DESCRIPTION
**Pull request by ajdapretnar**
##### Issue

Certain visualization widgets open with wrong initial size.

##### Description of changes
Introduce sizeHint that follows 16:9 ratio.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Honestly, I don't like this, but here's how a 16:9 ratio would look like.

**Comment by astaric** [comment]
why 16:9?

**Comment by markotoplak** [comment]
> Why 16:9. 

Some designer said so  - I asked him why and he said it is a nice ratio. And supposedly it would be beneficial if our widgets follow a single ratio. (I think both are... Whoops, let's just say I am not that convinced)

**Comment by astaric** [comment]
I'd go with 1:1.6 as it is the same ratio A4 paper uses :) and that would probably be for the visualization itself, not the whole widget.

**Comment by markotoplak** [comment]
The designer was open about the ratio... He said we could try different options.

**Comment by ajdapretnar** [comment]
I don't think this will make it into 3.16. We didn't decide on the ratio. I can modify to 1:1.6, if you want.

**Comment by lanzagar** [comment]
Why wouldn't it make it into 3.16?
The code changes are minimal, and the current state is **_terrible_**.

I agree we have not decided on the appropriate size/ratio for a all of Orange or even just visualizations, but this should be renamed to "Fix Scatter Plot size" and merged before 3.16. I don't really care what the size is, anything will be better than the current default :)

So please rebase, and you can change the aspect ration while at it to whatever you find best.
The general topic will remain open after this, we just need a quickfix until we find the ultimate answer.

**Comment by ajdapretnar** [comment]
After discussing with @irgolic, we decided to got with @astaric's suggestion. Now Scatter Plot uses 1:1.6 ratio, but horizontally for SP, since the other way around simply doesn't look good. Can be merged before 3.16.

**Comment by kernc** [comment]
Btw, like 16:9, it's called [*16:10*](https://en.wikipedia.org/wiki/16:10) aspect ratio.

**Pull request merged**
