### PR TITLE
OWFile relocatable recent file paths

### PR DESCRIPTION
**Pull request by ales-erjavec**
Store/restore recent file paths based on a set of predefined known/fixed
search paths (including loaded workflow scheme relative path if available).

### CODE REVIEW

**Comment by ales-erjavec** [comment]
@janezd: Can you test this by downloading and extracting: https://www.dropbox.com/s/bujhb0yfbkqg8xw/test.zip?dl=0
It contains a .ows file and a datasets directory. When opening the workflow (using this branch) it should resolve the recent paths to include the files in the datasets subdirectory.

Other wise if there are no complaints, this is ready for merging.

**Comment by ales-erjavec** [comment]
One problem: creating a workflow on windows and opening it on UNIX-like system does not restore the items, although the reverse does work.

**Comment by janezd** [comment]
@ales-erjavec, tested on OsX: works like Charm. Great. Could you take care of Windows, too? As I understand, students will exchange .ows files, and we have a mixture of Windows and Os Xs.

**Comment by ales-erjavec** [comment]
Now also relocates between windows/posix systems.
Note: in order to create a relocatable workflow it is first necessary to save a .ows file and then reload it.

**Comment by janezd** [comment]
@ales-erjavec I did not get " it is first necessary to save a .ows file and then reload it.", and I can't try it (I don't have any Windows ready). If somebody creates a schema on Windows, saves it and sends it to somebody with Mac, will it work?

**Comment by ales-erjavec** [comment]
The save/reload comment was general and not related to windows. The file widget (and in more general terms the whole workflow model) is only made aware of the base directory location when loaded from an existing .ows file. Therefore it is necessary to first save a new scheme (as it does not yet have an associated file) and load it again (I am working on a solution that would notify/propagate the changed base directory to the widgets when the workflow is saved).

Otherwise the .ows files created on Windows can now be opened on OSX, Linux, ...

**Comment by kernc** [comment]
So this change would need to be applied in any data-loading widget? We have quite a couple ... with an outlook on more.

Would it not perhaps be easier on the widget developers (potentially many) to force their `recent_files` `Setting` (or equivalent (... `FileSetting`?)) be of particular `[dirname+'/'+basename, ...]` format (e.g. list of strings), and then at the ows-saving stage we rewrite all those dirnames to be ows-relative, with exception of the _datasets_ dir, which gets saved separately and is reconstructed correctly for each platform? Thus no extensive changes or code complexity is introduced in the data-loading widgets; only the use of `FileSetting`. Wouldn't ~this work?

I'm only asking because I see 146 lines of this PR added to owfile.py which is about 60% of its current size. :fearful:

**Comment by janezd** [comment]
@kernc, weren't you in favour of simplifying widget settings handlers? :) Analysing settings and rewriting them would be insanely complex, dangerous and unmaintainable.

You're right, though, that we should use class `RecentFiles` (and perhaps also what is currently in `_relocate_recent_files`?) should be used in other widgets as well. @ales-erjavec, you probably planned this, right? This would not add too much overhead, and it would be simple and safe.

**Comment by kernc** [comment]
> weren't you in favour of simplifying widget settings handlers?

Still am.

Obviously, you have to mark state-preserving attributes somehow. A simple, appropriately-named `Setting` sub-class could override its `__reduce__` and `__setstate__` (or whatever `Setting` objects use to pickle) to transparently relativize† the filepath strings of its list. Straightforward, SLOC-wise pretty miniscule (=maintainable), and surely not dangerous* if documented? Be it a single line change, I don't see it get much more simple, or how it counters my disposition.
```py
    recent_files = RecentFilesSetting([])
```

__*__ The crudeness of method that may safely work for `RecentFilesSetting` does not necessarily scale to other, potential new types of settings.

__†__ Only some paths are relativized. The paths that share a common prefix with the widget or an installed python package, respectively, aren't relativized but are instead resolved in a platform-dependent way.

**Comment by janezd** [comment]
Settings do not work like this.

**Comment by ales-erjavec** [comment]
The save/reload is no longer necessary. The path items get subsumed under the basedir on first (or subsequent) save.

**Comment by janezd** [comment]
I like the solution with signals and events.

I tested it: I cannot make it fail -- and it's not for lack of trying. :) I guess it's done and I can merge it?

**Comment by ales-erjavec** [comment]
>  ... I can merge it?

Yes

**Pull request merged**
