### PR TITLE
[ENH] OWParallelCoordinates: Plotly-based

### PR DESCRIPTION
**Pull request by kernc**
##### Issue
Fixes https://github.com/biolab/orange3/issues/2310

##### Description of changes
Remove defunct parallel coordinates widget; add [Plotly JS](https://plot.ly/python/) graphing library; use it for parallel coordinates widget.

##### Includes
- [X] Code changes
- [ ] Tests
- [x] Documentation

screenshot - 05192017 - 06 54 01 pm

### CODE REVIEW

**Comment by astaric** [comment]
I have played around with the widget. It behaves strangely.

* When I click on an attribute in the list, selection keeps changing as I move the mouse around (as if it did not register the mouse-up event).
* The color combo also sometimes selects an item that is different from the One O clicked.
* When I add a new Parallel Coordinates widget to the workflow, connect it to data and open it, it performs 1-2 resizes before the plot changes to correct size.
* I haven't found a way to remove the selection.
* If I click on Optimize Selected Dimension and the plot is displaying more than 9 variables, nothing happens.

I have stopped at this point :)

**Comment by astaric** [comment]
While I would really like to see this merged, It will not make it to the 3.7 release.

@BlazZupan, @janezd, could you take a look and comment on this new widget? If major changes are required, I would rather have it included in prototypes first and then promoted to the core when ready.

**Comment by kernc** [comment]
Was worth a try. 😄

**Comment by kernc** [comment]
For the time being, obsoleted by https://github.com/biolab/orange3-prototypes/pull/99.

**Pull request closed without merging**
