### PR TITLE
Remove documentation datasets

### PR DESCRIPTION
**Pull request by ajdapretnar**
##### Issue

We have too many documentation data sets in the File widget.
Remove most and keep only important ones.
Partially solves also #1040.
Depends on https://github.com/biolab/datasets/pull/76.

##### Description of changes
Remove redundant data and provide metadata for the remaining few. Also provide them all in the dropdown of the File widget.
Most data sets are now moved to the file.biolab.si server and provided (with descriptions!) in the Datasets widget.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
A comment here. A number of tests fail due to missing data sets, namely:
- adult-sample (977 i, 14f, categorical 2, missing)
- anneal (898i, 38f, categorical 5, missing)
- auto-mpg (398i, 8f, regression, missing)
- banking-crises (211i, 73f, datetime)
- breast-cancer-wisconsin-cont (683i, 9f - all numeric, classification 2)
- conferences (42i, 3f, metas)
- cyber-security-breaches (1055i, 7f, datetime, metas, missing)
- glass (214i, 9f - all numeric, classification 7)
- imports-85 (205i, 25f, regression, missing)
- ionosphere (351i, 32f - all numeric, classification 2)
- lenses (24i, 4f - all categorical, classification 3)
- monks-1 (556i, 6f - all categorical, classification 2)
- voting (435i, 16f - all categorical, classification 2, missing)
- wine (178i, 13f - all numeric, classification 3)
- zoo-with-images (15i, 5 features - all categorical, classification 3, metas, images)

I don't see any significant difference between some data sets, say, ionosphere and breast-cancer-wisconsin-cont. Or glass and wine. Or auto-mpg and imports-85. I believe some can be safely replaced.

**Comment by janezd** [comment]
We decided that `Orange.data.Table.from_server(name)` will download the data from the server (and cache it). Or something like this but as separate issue.

**Comment by thocevar** [comment]
You missed test10.tab used in test_normalize.py.

Widget tests should use test_filename from Orange.tests instead of relative addressing "../../../tests/datasets".

I think we can leave the MANIFEST as it was "recursive-include Orange/tests *.tab *.basket *.xlsx". It should pick up things from subfolders (including the xlsx_files). I don't know how the MANIFEST and PACKAGE_DATA from setup.py interact because xlsx_files were successfully included.

**Comment by janezd** [comment]
@ajdapretnar, this needed rebase, but I also rebased it to check if the failing test (it doesn't fail on other current PRs) are caused by this PR being based on an old master. No. It must be caused by something in this PR. I suspect it's cursed or something.

**Comment by thocevar** [comment]
Maybe the changes simply nudged the random generator in a bad direction. It fails on a TSNE test `test_bh_correctness`, where the expected result is not as random as it should be (it's too good). However, the following `test_fft_correctness` succeeds, although it's almost the same. It has a different gradient method, which shouldn't play a role with iterations set to zero? @pavlin-policar can you have a look at this?

**Comment by pavlin-policar** [comment]
Looking at the test, @thocevar is definitely right. The test in question first generates a random embedding, makes sure it's really random (with KNN accuracy < 0.6), runs t-SNE and again makes sure the results make sense with KNN. 

Setting the random seed should solve the issue. Apparently some random projections are still pretty good in the eyes of a KNN classifier.

```diff
diff --git a/Orange/tests/test_manifold.py b/Orange/tests/test_manifold.py
index 99127493c..cf332ea22 100644
--- a/Orange/tests/test_manifold.py
+++ b/Orange/tests/test_manifold.py
@@ -207,7 +207,8 @@ class TestTSNE(unittest.TestCase):
 
         # Set iterations to 0 so we check that the initialization is fairly random
         tsne = TSNE(early_exaggeration_iter=0, n_iter=0, perplexity=30,
-                    negative_gradient_method='bh', initialization='random')
+                    negative_gradient_method='bh', initialization='random',
+                    random_state=0)
         model = tsne(self.iris)
 
         # Evaluate KNN on the random initialization
@@ -228,7 +229,8 @@ class TestTSNE(unittest.TestCase):
 
         # Set iterations to 0 so we check that the initialization is fairly random
         tsne = TSNE(early_exaggeration_iter=0, n_iter=0, perplexity=30,
-                    negative_gradient_method='fft', initialization='random')
+                    negative_gradient_method='fft', initialization='random',
+                    random_state=0)
         model = tsne(self.iris)
 
         # Evaluate KNN on the random initialization

```

**Comment by ajdapretnar** [comment]
I can't believe it. Tests passed. The curse is broken. I think I'll open a bottle of bubbly for this special occasion. 🍾 
Thank you, @pavlin-policar for identifying the tSNE fix! 🙌

**Comment by janezd** [comment]
I wanted to merge it ... but do we need to merge https://github.com/biolab/datasets/pull/76 first?

**Comment by ajdapretnar** [comment]
Yes, please. Otherwise data sets will just go missing. 😱

**Pull request merged**
