### PR TITLE
[FIX] owimageviewer: Open local images directly

### PR DESCRIPTION
**Pull request by ales-erjavec**
Using QNetworkAccessManager to 'retrieve' many local files can lead
to temporarily running out of available file descriptors.

Presumably this is because the associated open fd is not closed
until the QNetworkReply is actually deleted (and not just closed).

### CODE REVIEW

**Comment by astaric** [comment]
I cannot reproduce the original problem on my machine. @BlazZupan, can you check if this solves the issue for you?

**Comment by ales-erjavec** [comment]
> I cannot reproduce the original problem on my machine. @BlazZupan, can you check if this solves the issue for you?

Try running orange-canvas like so:
```sh
(ulimit -n 150; orange-canvas;)
```
(adjusting the limit appropriately to trigger the error)

**Comment by janezd** [comment]
Perhaps related: trying to view the images from https://www5.cs.fau.de/fileadmin/research/datasets/fundus-images/all.zip in the Image Viewer on Windows shows the first 20 or so out of 45 images and then complains that it cannot open the file.

I've seen this on somebody's computer, but cannot replicate it neither on Mac nor on Windows.

**Comment by BlazZupan** [comment]
Works fine on Mac. Should be checked on Win.

**Comment by astaric** [comment]
I am merging this. Testing on windows can be done with daily builds, when they become available.

**Pull request merged**
