### PR TITLE
Heatmap ported from bio addon

### PR DESCRIPTION
**Pull request by nikicc**

### CODE REVIEW

**Comment by kernc** [comment]
Please block on https://github.com/biolab/orange3/pull/421 :pray:

**Comment by kernc** [comment]
Please use [`variable.is_discrete` (...) interface](https://github.com/biolab/orange3/pull/421#issuecomment-105538130) in new code.

**Comment by nikicc** [comment]
Changed type checking according to new interface.

**Comment by kernc** [comment]
:heart:

**Pull request closed without merging**
