### PR TITLE
[FIX] Learner: Generalize params and used_vals to all learners

### PR DESCRIPTION
**Pull request by pavlin-policar**
##### Issue
#2125 6.

##### Description of changes
The fix I've provided does basically one thing. We now expect every learner to have a `params` attribute. We also expect every learner to output a model with the `used_vals` field. These attributes seem very general to all learners and models and there doesn't seem to be any reason whatsoever for scikit wrapped learners to be special and have their own separate attributes on their public API. This makes everything very confusing and difficult to work with. By moving everything up to the base learner, it makes the API of any learners much simpler and more uniform.

In case this is not a desired solution, I can also provide a quick and dirty workaround that also fixes the main issue with SGD and other wrapped learners.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by janezd** [comment]
I have a dream that one day Orange will be free of scikit-learn.

I have an unpleasant feeling that this makes Orange's learners more scikitish. If these parameters will be no longer needed when we replace scikit's learners with well-behaving, properly implemented algorithms, I'd prefer not putting them into base learners.

**Comment by kernc** [comment]
Indeed, sklearn is a mature, stable, reliable, responsible, well-defined, disciplined and hygienic, well-tested, reasonably working, pragmatic, go-to state-of-the-art and industry-standard machine learning library with a huge developer and user community — as all such evidently awfully incompatible with what we're doing here. (Not sarcasm, actually.)

**Comment by pavlin-policar** [comment]
Tbh, I think we should remove the `params` attribute all together since it is only ever useful in scikit learners and should be "protected" at the very least. Also, it's only ever used in tests in `WidgetLearnerTestMixin`. I can probably rewrite these tests so they wouldn't be needed anymore. It might however be reasonable to have attributes on learners like in [`TreeLearner`](https://github.com/biolab/orange3/blob/master/Orange/classification/tree.py#L63-L67), without the `params` of course. What do you think?

**Comment by kernc** [comment]
The reason [sklearn tracks params](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/base.py#L212-L316) is aforementioned discipline. Looking forward, deffo not something we want to be bound by at all costs.

> I am also unsure of why the model somehow needs the parameters...

So it knows what set of learner params led to it. So it can be reproduced. In theory.

**Comment by pavlin-policar** [comment]
> So it knows what set of learner params led to it. So it can be reproduced. In theory.

Well, yes, but so then why do only sklearn learners have this? And also wouldn't that be an argument to make for the learners to also have their own `params`?

I'd like to just remove `params` from the public API altogether and let sklearners use them internally, because really the only place where this is actually used is in one or two tests that can be changed.

**Pull request closed without merging**
