### PR TITLE
[ENH] Predictions: Update splitter on resize

### LINKED ISSUE #4430: Predictions: smarter resizing
**Is your feature request related to a problem? Please describe.**
Predictions widget has a very interesting approach to resizing. Main area is uniformly resized, meaning the model (left) part and data (right) part are resized both at the same time. This often makes the model part full of white space and then the user has to drag the parting line around to adjust it.

**Describe the solution you'd like**
Resizing the left part would stop once all the learners are visible.
Probably not easy to implement. Perhaps even impossible. But it would be nice.

**Additional context**
Left part too big, right part too small. It is annoying.
Screen Shot 2020-02-17 at 11 59 10

### PR DESCRIPTION
**Pull request by janezd**
##### Issue

Fixes #4430.

Fails (and will continue to fail) at coverage.

##### Description of changes

Update splitter on resize event.
 
##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
I personally love this fix, but a few more people should probably agree this is the desired behaviour. @markotoplak @lanzagar @PrimozGodec

**Comment by lanzagar** [comment]
I definitely think it is better than before.
But in the (rare?) case when the splitter is manually changed I find the abrupt jump on resize a bit jarring. Maybe it would be best to keep the left size constant on resizes and stretch/shrink just the data view? Not sure if that complicates the implementation?

**Comment by janezd** [comment]
> Maybe it would be best to keep the left size constant on resizes and stretch/shrink just the data view?

Like this?

- When the left part is changed, the splitter would reset to fit the left side. (Like it does now on resize.)
- The user can manually move it.
- When the window is resized, the left side would keep the same (no matter whether it was set automatically or by the user).

**Comment by janezd** [comment]
> Maybe it would be best to keep the left size constant on resizes and stretch/shrink just the data view?

Would this be OK?

- When the left part is changed, the splitter would reset to fit the left side. (Like it does now on resize.)
- The user can manually move it.
- When the window is resized, the left side would keep the same (no matter whether it was set automatically or by the user).

**Comment by janezd** [comment]
I changed it as described above.

**Comment by lanzagar** [comment]
:+1:

**Pull request merged**
