### PR TITLE
[FIX] File widget gives reader error 

### LINKED ISSUE #3349: File widget gives "reader error" on empty URL
##### Orange version

Any recent.

##### Expected behavior

In the file widget, selecting URL when the line edit is empty should output None as data, but without reporting any error.

##### Actual behavior

The widget informs the user about the error when reading the data.

### PR DESCRIPTION
**Pull request by AndrejaKovacic**
##### Issue

Fixes #3349

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by janezd** [comment]
There is another situation where a similar bug could occur. If `self.source == self.LOCAL_FILE`, `_get_reader` assumes that `self.recent_paths` is not empty. Initially it indeed contains files from documentation, but these can be later replaced by user files. If those are removed from disk, Orange will, I assume, remove them from `self.recent_paths` so it will be empty. If this happens, `path` will be `None` and `reader_class(path)` will return `None`.

I suppose you need to add

```
if path is None:
    return self.NoFileSelected
```

after `path = self.last_path()`.

(This is also the reason why I called the singleton `NoFileSelected` and not `NoUrl`.)

**Comment by ajdapretnar** [comment]
I would also kindly point out some redundant commits, which I suggest get sorted before merging. :)

**Comment by janezd** [comment]
@ajdapretnar, you should work in diplomacy.

**Comment by janezd** [comment]
Here's a test you can add.

```
    def test_nothing_selected(self):
        widget = self.widget = \
            self.create_widget(OWFile, stored_settings={"recent_paths": []})
        
        widget.Outputs.data.send = Mock()
        widget._try_load()
        widget.Outputs.data.send.assert_called_with(None)

        widget.Outputs.data.send.reset_mock()
        widget.source = widget.URL
        widget._try_load()
        widget.Outputs.data.send.assert_called_with(None)
```

**Comment by AndrejaKovacic** [comment]
Replaced by  #3402.

**Pull request closed without merging**
