### PR TITLE
[ENH] DBSCAN widget

### PR DESCRIPTION
**Pull request by PrimozGodec**
#### Description of changes

In discussion with @ajdapretnar we decided to move DBSCAN widget to core Orange. With this PR we move fixed DBSCAN widget to Orange.

Besides moving the DBSCAN widget this PR also introduce a graph that allows selection. That component is now called from OWPCA and OWDBCAN.

 Note: When testing makes sure to test PCA widget too.

##### Includes
- [X] Code changes
- [X] Tests
- [x] Documentation

### CODE REVIEW

**Comment by PrimozGodec** [comment]
I think the widget is ready to merge. @BlazZupan do you have any comment regarding the widget design.

**Comment by BlazZupan** [comment]
Works as expected on the painted data, but then may have some problems with other kinds of data sets:

- the widget crashes on brown-selected (report below)
- the 4-distance graph is empty on heart_disease

```
Traceback (most recent call last):
  File "/Users/blaz/.virtualenvs/orange/lib/python3.7/site-packages/orangecanvas/scheme/signalmanager.py", line 718, in __process_next
    self.process_queued()
  File "/Users/blaz/.virtualenvs/orange/lib/python3.7/site-packages/orangecanvas/scheme/signalmanager.py", line 476, in process_queued
    self.process_node(node_update_front[0])
  File "/Users/blaz/.virtualenvs/orange/lib/python3.7/site-packages/orangecanvas/scheme/signalmanager.py", line 523, in process_node
    self.send_to_node(node, signals_in)
  File "/Users/blaz/.virtualenvs/orange/lib/python3.7/site-packages/orangewidget/workflow/widgetsscheme.py", line 774, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Users/blaz/.virtualenvs/orange/lib/python3.7/site-packages/orangewidget/workflow/widgetsscheme.py", line 808, in process_signals_for_widget
    handler(*args)
  File "/Users/blaz/Documents/dev/orange3/Orange/widgets/unsupervised/owdbscan.py", line 187, in set_data
    self.unconditional_commit()
  File "/Users/blaz/Documents/dev/orange3/Orange/widgets/unsupervised/owdbscan.py", line 128, in commit
    self.cluster()
  File "/Users/blaz/Documents/dev/orange3/Orange/widgets/unsupervised/owdbscan.py", line 137, in cluster
    ).get_model(self.data_normalized)
  File "/Users/blaz/Documents/dev/orange3/Orange/clustering/clustering.py", line 85, in get_model
    model = self.fit_storage(data)
  File "/Users/blaz/Documents/dev/orange3/Orange/clustering/clustering.py", line 92, in fit_storage
    return self.fit(data.X)
  File "/Users/blaz/Documents/dev/orange3/Orange/clustering/clustering.py", line 95, in fit
    return self.__returns__(self.__wraps__(**self.params).fit(X))
  File "/Users/blaz/.virtualenvs/orange/lib/python3.7/site-packages/sklearn/cluster/dbscan_.py", line 351, in fit
    **self.get_params())
  File "/Users/blaz/.virtualenvs/orange/lib/python3.7/site-packages/sklearn/cluster/dbscan_.py", line 140, in dbscan
    raise ValueError("eps must be positive.")
ValueError: eps must be positive.
```

**Comment by PrimozGodec** [comment]
@BlazZupan it is fixed now

**Comment by ajdapretnar** [comment]
Fails on sparse. Perhaps a quick fix with an error message to prevent it from crashing?

**Comment by PrimozGodec** [comment]
@ajda it also works on bag-of-words data now.

**Pull request merged**
