### PR TITLE
[ENH] Feature Statistics: Move from prototypes to core

### PR DESCRIPTION
**Pull request by pavlin-policar**
##### Issue
https://github.com/biolab/orange3-prototypes/issues/165

##### Description of changes
Move Feature Statistics widget to core.

##### Includes
- [X] Code changes
- [X] Tests
- [x] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Could you include the documentation as well? Thanks!

**Comment by ajdapretnar** [comment]
Are we waiting to stop testing on Py3.4 to merge this one? I see only tests for Py3.4 are failing. Then we should probably wait for tests to pass on 3.7, no?

**Comment by pavlin-policar** [comment]
Yes, this doesn't work with Python 3.4, once it's removed from CI, this can be merged.

**Comment by lanzagar** [comment]
Python 3.4 was removed from travis testing, but tests still fail on python 3.5 with PyQt4.
I guess we need to be fine with dropping support for PyQt4 too, before merging (or make this compatible).
Anyone thinks we should keep supporting it, or are we all fine with requiring PyQt5? @ales-erjavec?

**Pull request merged**
