### PR TITLE
[ENH] New widget: Aggregate Columns

### LINKED ISSUE #5066: Merge columns into one
- [ ] **What's your use case?**

I have a dataset, where I wish to combine two or more columns into a single column, say a sum of values.

- [ ] **What's your proposed solution?**

Perhaps add a widget to enable merging (joining) columns with several aggregation methods (sum, mode, mean).

- [ ] **Are there any alternative solutions?**
Perhaps this is just my special use case. Tell me this is too specific and close it. Just an idea.

### PR DESCRIPTION
**Pull request by janezd**
##### Issue

Closes #5066.

Builds on #5251.

Screenshot 2021-02-11 at 18 10 47

##### Description of changes

Add a new widget.

##### Includes
- [X] Code changes
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by janezd** [comment]
If all variables are `TimeVariable`, output `TimeVariable`.

**Comment by janezd** [comment]
@ajdapretnar, could you check this and write the documentation if you think it's OK?

I'm asking you this just because you've more experience in this. You can tell me to do it myself and I will.

**Comment by ajdapretnar** [comment]
I will, but on Monday.

**Comment by ajdapretnar** [comment]
I have everything ready, but I can't build widget.json catalogue, because the widget is missing an icon. :/

**Comment by ajdapretnar** [comment]
Ok, I've added the documentation with a manually created widget.json. Do not try this at home. Might cause issues on the website due to the missing icon. :(

**Comment by janezd** [comment]
@BlazZupan will ask @larazupan to draw an icon.

**Comment by BlazZupan** [comment]
Works as intended :)

**Pull request merged**
