### PR TITLE
[FIX] Error Reporting: open encode as unicode

### PR DESCRIPTION
**Pull request by jerneju**
##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/204303618/

**Comment by janezd** [comment]
My first question after seeing this PR was --- why?

Is this needed because `scheme_to_ows_stream` saves as utf-8? Please provide better description of PRs: what they are fixing, how, what is needed to reproduce the bug (if applicable)... to make the reviewers' work easier.

**Comment by janezd** [comment]
Is this still WIP? Plus, can you answer the above question so we can proceed with the PR?

**Comment by jerneju** [comment]
I have not reproduced this bug yet, so now I am (temporarily?) closing this PR.

**Comment by ales-erjavec** [comment]
Run `LC_ALL=C orange-canvas`
Add some widget to the workflow, rename it to some non ascii name and trigger an exception (in some way):

```
-------------------------------------------------------------------------------
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/mock.py", line 1157, in patched
    return func(*args, **keywargs)
  File "/Users/aleserjavec/workspace/orange3/Orange/canvas/application/errorreporting.py", line 229, in handle_exception
    data['_' + F.WIDGET_SCHEME] = f.read()
  File "/Users/aleserjavec/virtual/orange3/bin/../lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 237: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aleserjavec/workspace/orange3/Orange/canvas/application/outputview.py", line 228, in __call__
    self.handledException.emit(((exc_type, exc_value, tb), self._canvas))
SystemError: <built-in method emit of PyQt5.QtCore.pyqtBoundSignal object at 0x125cd9558> returned a result with an error set
```

**Comment by jerneju** [comment]
Now I reproduced this error, tested it and this fix works.

**Pull request merged**
