### PR TITLE
[FIX] Fixes for scikit-learn 1.0

### PR DESCRIPTION
**Pull request by janezd**
##### Issue

Tests fail after release of scikit-learn 1.0.

- Scikit's fit checks whether the object has `columns` to distinguish between arrays and pandas frame. `Orange.data.Table` also has `columns`, but with different content, which caused a problem when (incorrectly) passed to scikit.
- ROC has tests for tooltips, which use test results for Titanic with kNN. Scikit changed something in kNN so that all returned probabilities are 0 or 1 (when k=5, this is not entirely unexpected).

##### Changes

- I fixed the call to kNN to pass an array `X`, not the whole `Table`.
- The offending test for ROC now uses artificial test results, not results from an actual model.

**To be considered:** `Orange.data.Table`'s property `columns`, which contains an instance of this: https://github.com/biolab/orange3/blob/03e8adaf41dac18d747c7f47afd7262c493fa951/Orange/data/table.py#L190  is unknown, strange, useless and to my knowledge unused.  I assume it was there for easier access to columns when working with Orange interactively. I would just remove it without any deprecation period.

##### Includes
- [X] Code changes
- [x] Tests
- Documentation N/A

### CODE REVIEW

**Comment by janezd** [comment]
I fixed the failing tests, but can't reproduce core dumps on Mac. Help wanted.

**Comment by markotoplak** [comment]
I merged as is.

I tried reproducing the segfaults locally. At first, I could not, but after I installed xgboost (an optional Orange dependency) it reliably segfaults on my 10.14 Mac. I just need to do the following in a fresh virtualenv:

```
pip install orange3
pip install xgboost
python -m unittest Orange.tests
```

For xgboost to work, you also need libomp. Before trying anything, do `brew install libomp`.

@janezd, can you replicate?

**Comment by janezd** [comment]
I can. `test_all_models_work_after_unpickling` segfaults after installing xgboost (and libomp).

**Comment by janezd** [comment]
Actually, the learner just crashes, always. 

```
>>> XGBLearner()(Orange.data.Table("iris"))
Segmentation fault: 11
```

**Comment by janezd** [comment]
We may be experiencing https://github.com/dmlc/xgboost/issues/7156: the crash happens at the same point, but if during debugging I change the value of variable `threads` from `-1` to `1`, it does not crash here (but crashes later, perhaps for a related reason).

Xgboost 1.5.0rc was released 4 days ago, and release is planned for Oct 11. I suggest we wait it out; till then, we can add a (time-bombed) exclusion for xgboost tests on MacOs.

**Comment by markotoplak** [comment]
That was a got find! Let's hope that 1.5 fixes this segfault and perhaps also #5599.

**Pull request merged**
