### PR TITLE
io, OWFile: if URL without scheme, assume http by default

### PR DESCRIPTION
**Pull request by kernc**
##### Issue
https://github.com/biolab/orange3/issues/2388

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jerneju** [comment]
screenshot_20170609_122356

**Comment by kernc** [comment]
~~Should~~Might work now.

**Comment by lanzagar** [comment]
Tests fail. Please fix.

Test with more urls.

Why lstrip?

**Comment by kernc** [comment]
> Tests fail. Please fix.

I don't know why the test fails. Please help.

> Test with more urls.

What other URLs are reasonable to test with?

**Comment by astaric** [comment]
The failing test on python3.4 was caused by a call to a method that has been added in Qt5. After replacing the call the test passes (locally), let's see what happens on travis.

**Pull request merged**
