### PR TITLE
Distances: data info displayed in the status bar

### PR DESCRIPTION
**Pull request by aturanjanin**
##### Description of changes
Input/output data info displayed in the status bar.

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by PrimozGodec** [comment]
The output here is a distance matrix which is N x N matrix. Currently, we just show the length of the matrix. Should we show both the height and width of the matrix instead? I know it is always a square matrix but I think users would have a better feeling if they see something like `150 x 150`.

**Comment by janezd** [comment]
I don't disagree. :) I'd use 150×150 -- no spaces and symbol × instead of letter x.

**Comment by aturanjanin** [comment]
So we should put 150×150 into both, summary and details?

**Comment by janezd** [comment]
Maybe. Let's decide tomorrow.

**Comment by PrimozGodec** [comment]
Note: `self.info.set_output_summary(summary, summary)` is used since in the cases with string summary description is not set automatically to same value than it is done for int summary. I suggest unifying those behaviours.

**Pull request merged**
