### PR TITLE
Replace Orange canvas icons with a newer design

### LINKED ISSUE #2953: Update icons
Update icons with the Orange character in the repository with the (long time ago) refreshed logo on orange.biolab.si

Icons to update are in
scripts/windows/
distribute/
Orange/canvas/icons

### PR DESCRIPTION
**Pull request by markotoplak**
The "newer" design is used on our home page for years.

Closes #2953

### CODE REVIEW

**Comment by markotoplak** [comment]
I haven't updated the .ows document icons and installation icons yet.

TODO: 
- [ ] ./scripts/macos/skeleton.app/Contents/Resources/schema.icns
- [ ] ./scripts/windows/OrangeOWS.ico
- [ ] ./scripts/windows/OrangeInstall.ico

There is a tool "docerator" that can make document icons on a mac, but it gives me strange results.

**Comment by astaric** [comment]
I have contributed the missing mac icons. (new orange logo overlayed over the default document/disk image icon)

**Comment by markotoplak** [comment]
Thank you, @astaric

**Comment by astaric** [comment]
This PR now includes all the icons. Ready for another review.

**Comment by markotoplak** [comment]
Do we need to test it somehow if they make into dmg's and installers?

**Comment by astaric** [comment]
Probably :)

I have tested both mac and windows and icons in the installers are new ones.

**Pull request merged**
