### PR TITLE
[FIX] Select Rows: do not crash when string to discrete

### PR DESCRIPTION
**Pull request by jerneju**
##### Issue 1
screenshot_20170530_104408
screenshot_20170530_104445

##### Steps to reproduce the behavior 1
Put _File_ widget on a canvas and open _iris_. Skip all attributes except first for instance _sepal length_. Set it to **string** and **meta**. Connect _File_ widget and _Select Rows_. In _Select Rows_ select **contains** and write a letter in a box. And lastly in _File_ widget change **string** to **nominal** and click **Apply** button.

##### Issue 2
screenshot_20170530_124330
screenshot_20170530_124402

##### Steps to reproduce the behavior 2
Put _File_ widget on a canvas and open _iris_. Skip all attributes except first for instance _sepal length_. Set it to **string** and **meta**. Connect _File_ widget and _Select Rows_. In _Select Rows_ select **is outside** and write numbers in boxes. For instance, write **1** and **2**. And lastly in _File_ widget change **string** to **nominal** and click **Apply** button.

##### Description of changes
Work in progress.

##### Includes
- [ ] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/257496478/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/218977889/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/251723351/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/246359540/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/239673432/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/252117635/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/271931826/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/242170111/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/287306153/

**Comment by janezd** [comment]
Is this still WIP, as the comment (but not the title) suggests? Could you describe the issue - how to reproduce it, what causes it, how to fix it? Snapshots are usually uninformative; in this case, they may be useful to try to decipher how to reproduce the bug, but it would be so much better if you provided the description instead.

Based on the changes you made, this is probably related to settings. @astaric, did you take a look?

**Comment by astaric** [comment]
OWSelectRows does not store variable type in conditions. When a context is reused, filtering of setting values is only done by variable names, causing problems when variable shares the same name but not the same type.

What needs to be done: [is_valid_item](https://github.com/biolab/orange3/blob/master/Orange/widgets/data/owselectrows.py#L36) should return False when the stored condition was created with an incompatible variable type. How is the hard part, as there currently is no way to infer the variable type from condition alone.

Since this workaround is long and complicated, I would much rather add var_type to conditions list and handle older settings in a migration. I took a shot at it in https://github.com/astaric/orange3/commit/c810d0fa80b9383c24040810e11ca68b04e395ce 
It passes the tests in this PR though I am pretty sure it does not work (yet) :)

**Comment by jerneju** [comment]
@janezd : I have finally written above how to reproduce these two errors.

**Comment by janezd** [comment]
I agree with @astaric, this should be fixed by storing variable types.

**Pull request closed without merging**
