### PR TITLE
CI: Install pymssql separately

### PR DESCRIPTION
**Pull request by janezd**
An attempt at fixing failing tests on macOS with Python >= 3.11.

### CODE REVIEW

**Comment by janezd** [comment]
I give up. I guess we should abandon tests on macOS that requires pymssql until pymssql installation is fixed. I hope we distribute a working version of pymssql in released Orange?

**Comment by markotoplak** [comment]
I think (did not check) we don't even distribute pymssql. And if we do, we have tests there anyway that would catch if something was wrong.

**Comment by janezd** [comment]
> we have tests there

Where?

**Comment by markotoplak** [comment]
> > we have tests there
> 
> Where?

When we create packages, we run all the tests on the installed package.

**Pull request closed without merging**
