### PR TITLE
OWRank: Get scores from linear regression and random forest

### PR DESCRIPTION
**Pull request by VesnaT**
OWRnk can now get signals from OWLinearRegression and OWRandomForest.
Therefore Liner regression learner and Random forest learner extend Scorer, which is additional input to OWRank.

When attribute is continuized, an average of related scores in given.

### CODE REVIEW

**Comment by kernc** [comment]
What about Logistic Regression?

**Comment by kernc** [comment]
The problem with Linear Regression is that it can assign significant _negative_ weights, which will get important attributes sorted below unimportant ones that have zero weight. Would it make sense to instead take the absolute value of weight?

**Comment by VesnaT** [comment]
Logistic Regression will be added when this PR is merged..

**Comment by kernc** [comment]
Disagreed. :+1: 

Also seems to be blocked on https://github.com/biolab/orange3/pull/825.

**Comment by janezd** [comment]
@kernc @VesnaT I agree, we should take absolute values of coefficients. Alternatives are to compute some statistics (e.g. 1 - p_value) or to sort by absolute values. Note that some for some scores lower values can be better, so each score should have an associated cmp function (e.g. le(x), ge, ge(abs(x))...)

**Comment by kernc** [comment]
> so each score should have an associated cmp function (e.g. le(x), ge, ge(abs(x))...)

Not sure I fully agree there. When the user sorts the TableWidget's column, they expect a consistent ascending/descending behavior and the red visual cue lines to mean what they say, namely that `-2 < 0.1` holds.

Since we never promise to output the raw coefficients (or similar), couldn't transforming the results (per scorer), like `abs(weights)`, `1/abs(weights)`, `1 - scale(weights, 0, 1)` (..., as appropriate), also work?

**Comment by astaric** [comment]
This PR adds Scorer input to the Rank widget and adds a LearnerScorer class, that can fix scores created on continuized dataset.

Adding cmp to scores is out of scope, an so is determining what is the correct way to score features using linear regression.

@janezd @kernc if you think that Linear regression scoring is not ok, I suggest that the related code is moved to a separate pull request and the rest is merged (Rank using Scorers and RF scorer).

**Comment by kernc** [comment]
@astaric With logistic regression and RF regressor missing, this PR seems incomplete.

**Comment by kernc** [comment]
Please rebase on latest master.

**Pull request merged**
