### PR TITLE
[RFC] TreeViewer: Pinch to zoom

### PR DESCRIPTION
**Pull request by astaric**
An attempt at solving #1303.

I have ported the Qt4 Pinch Zooming example (http://doc.qt.io/qt-4.8/qt-touch-pinchzoom-example.html) to work with our tree widget and modified the code a bit (if the distance between fingers changes for more than 20%, its a pinch to zoom, otherwise, it is a pan event).

Only tested in on OSX and it kind of works. Could use some testing on other platforms and general suggestions if there is another, cleaner way to do this.

### CODE REVIEW

**Comment by kernc** [comment]
Would you make a `gui.GraphicsView(QGraphicsView)` all other widgets' `QGraphicsViews` would extend from?

**Comment by astaric** [comment]
Could do. Are there any other features we could pull into this new class?

**Comment by kernc** [comment]
Auto setting [properties](https://doc.qt.io/qt-5/qgraphicsview.html#properties) to most sane and cross-platform-compatible (overridable) values. Kind of like [what is done for TableView](https://github.com/biolab/orange3/blob/20a860c684f510203d8f2dcd915e359f25b804ae/Orange/widgets/gui.py#L41).

**Comment by kernc** [comment]
Feel like working on this further? :smiley:

**Comment by astaric** [comment]
Nah. The current version is not good enough for practical use and I really hate that I have to manually decide whether a gesture is a pan or a zoom one (I fitted the parameters to my trackpad, but they might be completely off for different hardware). I would be really nice, if this functionality would be provided by OS/Qt

**Comment by kernc** [comment]
With [`QGesture`](https://doc.qt.io/qt-4.8/gestures-overview.html), for example.

**Pull request closed without merging**
