### PR TITLE
ci: start python 3.8 testing

### PR DESCRIPTION
**Pull request by JakaKokosar**

### CODE REVIEW

**Comment by JakaKokosar** [comment]
There is an issue with Windows + python 3.8 + pyqtgraph 0.10.0

issue: https://github.com/pyqtgraph/pyqtgraph/issues/1108

```
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\unittest\__main__.py", line 18, in <module>
    main(module=None)
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\unittest\main.py", line 100, in __init__
    self.parseArgs(argv)
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\unittest\main.py", line 147, in parseArgs
    self.createTests()
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\unittest\main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\unittest\loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\unittest\loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "D:\a\orange3\orange3\.tox\py\Lib\site-packages\Orange\__init__.py", line 33, in <module>
    import pyqtgraph  # import pyqtgraph first so that it can detect Qt5
  File "D:\a\orange3\orange3\.tox\py\Lib\site-packages\pyqtgraph\__init__.py", line 204, in <module>
    from .graphicsItems.VTickGroup import * 
  File "D:\a\orange3\orange3\.tox\py\Lib\site-packages\pyqtgraph\graphicsItems\VTickGroup.py", line 7, in <module>
    from .. import functions as fn
  File "D:\a\orange3\orange3\.tox\py\Lib\site-packages\pyqtgraph\functions.py", line 17, in <module>
    from . import debug
  File "D:\a\orange3\orange3\.tox\py\Lib\site-packages\pyqtgraph\debug.py", line 11, in <module>
    from . import ptime
  File "D:\a\orange3\orange3\.tox\py\Lib\site-packages\pyqtgraph\ptime.py", line 24, in <module>
    cstart = systime.clock()  ### Required to start the clock in windows
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by janezd** [comment]
`time.clock` was deprecated in 3.3 and was removed in 3.8. 

https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals

**Comment by markotoplak** [comment]
> There is an issue with Windows + python 3.8 + pyqtgraph 0.10.0

Fun. Conda-forge patched their pyqtgraph because of this: conda-forge/pyqtgraph-feedstock#10.

I do not know what to do about it. These tests will only pass when a new version of pyqtgraph gets released. An option would be to try to make Orange compatible with pyqtgraph 0.11.0rc0 (now it is not; Orange is only compatible with pyqtgraph develop) and require that.

**Comment by markotoplak** [comment]
I removed Python 3.8 testing on Windows.

**Pull request merged**
