### PR TITLE
Remove files for building installers

### PR DESCRIPTION
**Pull request by markotoplak**
Installers were moved to orange3-installers. 3.25.0 was already released from installers there. These files are now stale.

### CODE REVIEW

**Comment by vinbrule** [comment]
Hello, can you point me to the location of  orange3-installers? I couldn't find it here. Bests

**Comment by janezd** [comment]
Google can't help? And git's search also doesn't find it? :)

**Comment by ales-erjavec** [comment]
> Hello, can you point me to the location of orange3-installers?

https://github.com/ales-erjavec/orange3-installers

**Comment by vinbrule** [comment]
Thank so much

**Pull request merged**
