### PR TITLE
[WIP] report: report_plot works with QWidget

### PR DESCRIPTION
**Pull request by kernc**

### CODE REVIEW

**Comment by astaric** [comment]
Is this used on any of the widgets already so I can see it in action?

**Comment by kernc** [comment]
QGraphicsView from Network Explorer (report code https://github.com/biolab/orange3-network/pull/14).

**Comment by astaric** [comment]
Using the suggested widget, I got the following report when reporting on a zommed in version of a graph.

screen shot 2016-09-15 at 14 17 33

Can you check whether the problem lies in report generating code or in the widget itself?

**Comment by astaric** [comment]
Have you managed to take a look at the problem I mentioned above? If the problem is not related to this PR, are there any other widgets that I can see the change in action?

**Comment by kernc** [comment]
The only case I had for plotting QWidgets in Report was in Network Explorer, but there the plot source can easily be switched from QGraphicsView to its scene, which is already supported. Therefore this PR is unneeded.

**Comment by ajdapretnar** [comment]
> but there the plot source can easily be switched from QGraphicsView to its scene

I'd appreciate that so much! 🙌 Would it not make plotting a legend also easier (or at least bearable)?

**Pull request closed without merging**
