### PR TITLE
[FIX] Windows installers: Python lookup

### PR DESCRIPTION
**Pull request by ales-erjavec**
##### Issue

* gh-2826
* Regular 32-bit installer for Python >= 3.5 would fail to find the correct Python installation (looks for 64 bit python instead)

##### Description of changes

* Validate conda install layout
* Fix registry key lookup for 32 bit python >= 3.5

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by astaric** [comment]
Is there a way to specify the order of entries in the start menu? Currently Orange Command Prompt comes before Orange. (miniconda installer)

**Comment by ales-erjavec** [comment]
Orange comes first for me:
screen shot 2017-12-20 at 10 08 35

**Comment by astaric** [comment]
I was testing it on windows 7, I guess windows changed the default ordering since then. If Orange is listed first on recent versions of windows, it is ok

screen shot 2017-12-20 at 10 39 35

**Comment by astaric** [comment]
I have tested the miniconda stuff and it works. Not sure how to reproduce the regular installer problem though.

**Comment by ales-erjavec** [comment]
> Not sure how to reproduce the regular installer problem though.

The 32-bit regular installers for Python >= 3.5 did not work at all. They would fail with "Python installation failed (cannot determine Python installation prefix)" or with a pip error "...win32.whl is not a supported wheel on this platform" depending on whether 64 bit Python was already installed.

To reproduce the error create a installer on master
```
./scripts/windows/build-win-installer.sh --python-version 3.6.3 --platform win32 --pip-arg={orange3==3.8.0,PyQt5,-f,https://orange.biolab.si/download/files/wheelhouse}
```

**Comment by astaric** [comment]
Thanks. As the new installers work (for me) I am merging this.

**Pull request merged**
