### PR TITLE
[ENH] owtable: output sorted data

### LINKED ISSUE #4597: Table widget could output sorted data
#### Write a clear and concise description of what the problem is.

I sorted a table by some column (i.e. I sorted countries by number of confirmed Covid-19 cases per million). Then I wanted to know the rank of Slovenia. The table's horizontal header shows row numbers from the original data, which is correct, but not helpful in this case. So I hoped that if I connect another table widget to this one, I get re-ordered data. This is not the case.

#### Describe the solution you'd like

I'd like the output data in the some order as presented in the table, if this is not too difficult.

### PR DESCRIPTION
**Pull request by JakaKokosar**
##### Issue
Fixes #4597

##### Includes
- [X] Code changes
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by JakaKokosar** [comment]
This was just a quick look at this issue. Still needs improvements and testing. 

For example, data is not committed if you change the sorting order.

**Comment by janezd** [comment]
This must be one of the weirdest [ENH] PRs ever: it adds functionality by removal of 33 lines, and a minor modification of a single line. Kudos.

It looks OK, just add the missing signals and tests, when you have time.

**Comment by JakaKokosar** [comment]
Sorry for the delay. I will wrap this up today. Hopefully.

**Comment by janezd** [comment]
Is this now still WIP or can I review and merge (if OK)?

**Comment by JakaKokosar** [comment]
> Is this now still WIP or can I review and merge (if OK)?

I added additional tests. If CI passes I think its OK to merge.

**Pull request merged**
