### PR TITLE
[FIX] Paint Data: now stores data in list and not np.array

### PR DESCRIPTION
**Pull request by jerneju**
##### Issue
https://sentry.io/biolab/orange3/issues/240133185/

##### Steps to reproduce the behavior
One way to reproduce this behavior:
Use _Paint Data_ widget and draw some points. Then save it. Close the Orange. Open the Orange and then load the file and close the Orange again. Error should be thrown.

These steps were tested in Orange versions _master_, _3.4.2_, _3.4.1_ and _3.3.12_. In all those versions error occurred.

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/240133185/

**Comment by astaric** [comment]
How can the error be reproduced by user? (= not in code)?

**Comment by jerneju** [comment]
@astaric : Now added above.

**Comment by jerneju** [comment]
Changed _Paint Data_. Now stores points in `List`. Therefore settings are saved in _literal_ format and not _pickle_.

**Pull request merged**
