### PR TITLE
OWSelectColumns: Fixup UI

### PR DESCRIPTION
**Pull request by irgolic**
Screenshot 2021-02-01 at 21 29 24

(might not look the same with a non-master version of orange-widget-base)
##### Description of changes
- remove Up/Down buttons
- fit target box to contents
- reorganize option and autocommit into buttonsArea
- simplified names of boxes

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by irgolic** [comment]
Also, I know we've spent hours on the new checkbox

but can I suggest we invert it? `Ignore new variables by default`, something like that? It seems easier to word when it's inverted. The word 'select' doesn't really connect with the UI (it should mention Features).

**Comment by markotoplak** [comment]
I added this to the milestone. As I understood, the checkbox was not released yet, so we do not need to worry about setting migration (please double check this). Perhaps also use a new name for the setting.

**Comment by PrimozGodec** [comment]
> but can I suggest we invert it? Ignore new variables by default, something like that? It seems easier to word when it's inverted. The word 'select' doesn't really connect with the UI (it should mention Features).

Implemented in https://github.com/biolab/orange3/pull/5237

**Comment by irgolic** [comment]
Merged with https://github.com/biolab/orange3/pull/5013

**Pull request closed without merging**
