### PR TITLE
[FIX] Support Sparse Data in Domain Editor

### LINKED ISSUE #2188: File's Domain Edit Breaks Loading Pickle With Sparse Data
##### Orange version

3.5.dev

##### Expected behavior
One is able to load data with sparse features stored in pickle format.

##### Actual behavior
File widget crashes with:
```
Traceback (most recent call last):
  File "/Users/Niko/Projects/orange3/Orange/widgets/data/owfile.py", line 269, in browse_file
    self.load_data()
  File "/Users/Niko/Projects/orange3/Orange/widgets/data/owfile.py", line 322, in load_data
    self.apply_domain_edit()  # sends data
  File "/Users/Niko/Projects/orange3/Orange/widgets/data/owfile.py", line 404, in apply_domain_edit
    domain, cols = self.domain_editor.get_domain(self.data.domain, self.data)
  File "/Users/Niko/Projects/orange3/Orange/widgets/utils/domaineditor.py", line 231, in get_domain
    col_data = col_data.ravel()
  File "/Users/Niko/anaconda/envs/temporary/lib/python3.6/site-packages/scipy/sparse/base.py", line 576, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: ravel not found
```

##### Steps to reproduce the behavior
In text addon load some data and pass it through bag of words widget. Then save the data and try to load it using `File` widget.

##### Additional info (worksheets, data, screenshots, ...)
screen shot 2017-04-04 at 11 01 23

### PR DESCRIPTION
**Pull request by nikicc**
##### Issue

Fixes #2188.

##### Description of changes
Enhance `DomainEditor.get_domain` to handle sparse data. Also instead of returning a list of columns' the method itself merges them to appropriate `X`, `y` and `meta` arrays.

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jerneju** [comment]
Can you reduce complexity?

**Comment by jerneju** [comment]
```
Traceback (most recent call last):
  File "/home/jernej/Projects/Orange2/orange3/Orange/widgets/data/owfile.py", line 241, in select_file
    self.load_data()
  File "/home/jernej/Projects/Orange2/orange3/Orange/widgets/data/owfile.py", line 322, in load_data
    self.apply_domain_edit()  # sends data
  File "/home/jernej/Projects/Orange2/orange3/Orange/widgets/data/owfile.py", line 404, in apply_domain_edit
    domain, cols = self.domain_editor.get_domain(self.data.domain, self.data)
  File "/home/jernej/Projects/Orange2/orange3/Orange/widgets/utils/domaineditor.py", line 280, in get_domain
    col_data = self._to_column(col_data, is_sparse, dtype=object)
  File "/home/jernej/Projects/Orange2/orange3/Orange/widgets/utils/domaineditor.py", line 213, in _to_column
    raise ValueError('Cannot set dtype on sparse matrix.')
ValueError: Cannot set dtype on sparse matrix.
```

**Comment by nikicc** [comment]
@jerneju should be fixed now, please check again.

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/283621279/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/219559886/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/269413491/

**Pull request merged**
