### PR TITLE
[ENH] DomainEditor: Indicate changed variables with bold face font

### LINKED ISSUE #2673: File: Mark modifications in DomainEditor
There is no clear indication whether the header has been modified after the file has been loaded. (in the Columns part of the widget)

The least we could do is to indicate which rows have been modified, either with color or some other indicator (checkbox?). We could also use a Reset button which resets variables to their default values, it should be disabled if no modifications have been made.

Modifications are done manually by the user or restored from settings (when a dataset that has been modified is loaded again).

### LINKED ISSUE #3563: Domain Editor in File widget should have a Reset button

### PR DESCRIPTION
**Pull request by janezd**
##### Issue

Fixes #2673 and fixes #3563.

##### Description of changes

Model remembers the original data and implements `FontRole` to return a bold font if the line was changed.

I sincerely don't know how to reasonably test this. It's all just a game of signals.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by lanzagar** [comment]
Does not work correctly for me.
After some clicking, currently it fails even just opening the File widget and changing sepal width to meta (it does not become bold), then clicking Reload makes it bold and combinations of changes with clicking Reset, Apply, Reload almost always lead to inconsistencies.
(I cleared widget settings and it still fails as early as described above, which is strange, because at first I though it was working fine, until some random clicking).

**Comment by janezd** [comment]
It's amazing that it worked for me. The problem was in a list that had to be deepcopied, not just copied.

I noticed that changing a variable's position (e.g. feature -> meta) is correctly indicated with bold font, but has no effect on the output. This is an unrelated problem that already exists on master.

**Comment by janezd** [comment]
LOL, changing feature -> meta of course works. I was observing the output on Select columns, which just reversed any change -- because that's exactly what it does. :)

**Comment by ajdapretnar** [comment]
This works well for me after a short test. However, changes are indicated with italics not bold. I like it that way, but we could make it clear in the PR as well.

**Comment by janezd** [comment]
```
                font = QFont()
                font.setBold(True)
```

gives italic!? It's bold on my machine.

**Comment by ajdapretnar** [comment]
Sorry, I was being stupid. I was looking at Edit Domain, I obviously didn't read the PR title well enough. It is indeed in bold. And it works, too. I mean the one in File widget.

**Comment by markotoplak** [comment]
@janezd, I particularly like that reset button. Looks cool. :)

**Pull request merged**
