### PR TITLE
clustering/hierarchical: Check the input linkage matrix

### PR DESCRIPTION
**Pull request by ales-erjavec**
##### Description of changes

Validate the the input linkage matrix and raise an error if invalid

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by lanzagar** [comment]
If an error occurs in this validation, will that crash the widget and show the send error window? No new error catching was added, but maybe an existing check handles this as well?
@ajdapretnar can you test, since you can reproduce the original problem.

**Comment by ajdapretnar** [comment]
Yup, the error:


Exception:
ValueError: Linkage 'linkage' uses the same cluster more than once.
Module:
scipy.cluster.hierarchy:1421
Widget Name:
Hierarchical Clustering
Widget Module:
Orange.widgets.unsupervised.owhierarchicalclustering:976
Widget Scheme:
/var/folders/xn/5y86_zbd2f35vb02plps2f_r0000gn/T/ows-t_8rnxtm.ows.xml
Version:
3.5.0.dev0+f81d02c
Environment:
Python 3.5.2 on Darwin 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
Installed Packages:
AnyQt==0.0.8, Babel==2.4.0, Bottleneck==1.2.0, CacheControl==0.12.3, CommonMark==0.5.4, Genesis-PyAPI==1.2.0, Jinja2==2.9.5, MarkupSafe==1.0, Orange-Bioinformatics==2.6.19, Orange-Infrared==0.1.4, Orange3-Associate==1.1.3, Orange3-DataFusion==0.1.10, Orange3-Educational==0.0.3, Orange3-Geo==0.1.6, Orange3-ImageAnalytics==0.1.6, Orange3-Network==1.2.0, Orange3-Prototypes==0.5.0, Orange3-Text==0.2.4.dev0+3f6792e, Orange3-Timeseries==0.2.5, Orange3==3.5.0.dev0+f81d02c, Pillow==4.0.0, Pygments==2.2.0, Shapely==1.5.17.post1, Sphinx==1.5.3, alabaster==0.7.10, beautifulsoup4==4.5.3, boto==2.45.0, bz2file==0.98, certifi==2016.9.26, chardet==2.3.0, decorator==4.0.11, dill==0.2.5, docutils==0.12, gensim==0.13.4.1, h2==2.5.2, hpack==2.3.0, hyper==0.7.0, hyperframe==3.2.0, imagesize==0.7.1, joblib==0.10.3, keyring==9.0, keyrings.alt==1.2, lockfile==0.12.2, msgpack-python==0.4.8, networkx==1.11, nltk==3.2.2, numpy==1.11.3, numpydoc==0.6.0, oauthlib==2.0.1, observable==0.3.1, olefile==0.44, opencv-python==3.2.0.6, opusFC==1.1.0, pandas==0.19.2, patsy==0.4.1, pip==9.0.1, pycountry==17.1.8, pyqtgraph==0.10.0, python-dateutil==2.6.0, pytz==2016.10, recommonmark==0.4.0, requests-cache==0.4.13, requests-oauthlib==0.7.0, requests==2.12.4, scikit-fusion==0.2.1, scikit-learn==0.18.1, scipy==0.18.1, serverfiles==0.2, setuptools-git==1.1, setuptools==32.3.1.post20170108, simhash==1.7.1, simple-wbd==0.5.1, simplejson==3.10.0, six==1.10.0, slumber==0.7.1, smart-open==1.3.5, snowballstemmer==1.2.1, spectral==0.18, statsmodels==0.6.1, tweepy==3.5.0, typing==3.5.3.0, validate-email==1.3, wheel==0.29.0, wikipedia==1.4.0, xlrd==1.0.0
Machine ID:
Ajda
Stack Trace:
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3/Orange/canvas/scheme/widgetsscheme.py", line 822, in process_signals_for_widget
    handler(*args)
  File "/Users/ajda/orange/orange3/Orange/widgets/unsupervised/owhierarchicalclustering.py", line 976, in set_distances
    self._invalidate_clustering()
  File "/Users/ajda/orange/orange3/Orange/widgets/unsupervised/owhierarchicalclustering.py", line 1085, in _invalidate_clustering
    self._update()
  File "/Users/ajda/orange/orange3/Orange/widgets/unsupervised/owhierarchicalclustering.py", line 1039, in _update
    tree = tree_from_linkage(Z)
  File "/Users/ajda/orange/orange3/Orange/clustering/hierarchical.py", line 224, in tree_from_linkage
    linkage, throw=True, name="linkage")
  File "/Users/ajda/anaconda/envs/o3/lib/python3.5/site-packages/scipy/cluster/hierarchy.py", line 1421, in is_valid_linkage
    % name_str)
ValueError: Linkage 'linkage' uses the same cluster more than once.

Local Variables:
OrderedDict([('Z',
              array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          2.00000000e+00],
       [  2.00000000e+00,   1.15600000e+03,   0.00000000e+00,
          3.00000000e+00],
       [  3.00000000e+00,   1.15700000e+03,   0.00000000e+00,
          4.00000000e+00],
       ..., 
       [  2.30200000e+03,   2.30700000e+03,   6.28829935e+00,
          9.59000000e+02],
       [  2.29900000e+03,   2.30600000e+03,   6.67764287e+00,
          1.97000000e+02],
       [  2.30800000e+03,   2.30900000e+03,   1.32618588e+01,
          1.15600000e+03]])),
             ('n', 1155),
             ('name', 'linkage'),
             ('name_str', "'linkage' "),
             ('throw', True),
             ('valid', True),
             ('warning', False)])

**Comment by ales-erjavec** [comment]
I am not sure whether this is something that should be caught in the widget, as I am not certain whether scipy.clustering.hierarchy.linkage can be expected to always produce a linkage that encodes a tree (even if presented with a distance that is not euclidean and the selected linkage method requires them).

@ajdapretnar Can you please also check with scipy==0.19.0.

**Comment by ajdapretnar** [comment]
With scipy 0.19.0 it works great. :) No errors and the documents on the output correspond to the branch.
Should I merge? What do we do with folks that have scipy<0.19.0? Probably the error should still be caught somewhere...

**Comment by ales-erjavec** [comment]
I think https://github.com/scipy/scipy/pull/6790 was the fix.

The NN-Chain algorithm that scipy uses should otherwise always terminate with a valid linkage matrix even for ward linkage on a non euclidean distance matrix (according to [Daniel Müllner - Modern hierarchical, agglomerative clustering algorithms](https://arxiv.org/abs/1109.2378) on which the implementation itself is based)

**Comment by lanzagar** [comment]
We definitely do not want to be receiving error reports with crashes like the one @ajdapretnar posted.
If it was because of a fixed bug in scipy, we could just bump the version in requirements (latest is 0.19, while we require 0.11??). If we expect these kind of errors are possible in the future, we might want a nicer gui error - we can have a general error message about problems during clustering as a failsafe?

**Pull request merged**
