### PR TITLE
Setup.py lint subcommand

### PR DESCRIPTION
**Pull request by kernc**

### CODE REVIEW

**Comment by janezd** [comment]
How do I use this subcommand?

```
22:32 $ python setup.py lint
running lint
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by kernc** [comment]
Indeed, that's how you run it. It doesn't work. :laughing: 

Please paste the output of:
```bash
git remote -v | grep biolab
```

**Comment by janezd** [comment]
```
origin	http://github.com/biolab/orange3.git (fetch)
origin	http://github.com/biolab/orange3.git (push)
```

**Comment by kernc** [comment]
Please find it working in https://github.com/biolab/orange3/pull/1153

**Pull request merged**
