### PR TITLE
[FIX] OWBaseLearner: Use new-style signals for base widget

### LINKED ISSUE #2466: Logistic regression and linear regression widgets lost Coefficients outputs
Logistic regression and linear regression widgets lost Coefficients outputs (they are still in the code, but ineffective).

##### Orange version
master

##### Expected behavior
The widgets would have the output as they do in 3.4.4.

### PR DESCRIPTION
**Pull request by kernc**
Fix merging subclass' signals with OWBaseLearner's defaults.

##### Issue
Fixes #2466

##### Description of changes
Install new-style signals on OWBaseLearner, and merge defaults with addendums so that the unions persist.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by astaric** [comment]
Another take on this is in #2503. Can you take a look and comment?

**Comment by janezd** [comment]
I strongly prefer #2503 over #2499. #2503 inherits `Outputs` explicitly, while #2499 does it implicitly. Both need some magic, yet #2503 has less of it and it's less dark.

**Comment by kernc** [comment]
No question about it. Don't know what I was thinking. @nikicc convinced me this was hard, and probably with that in mind I tried to keep it complex. 😄

**Comment by nikicc** [comment]
@kernc you should've known by now not to listen to me 😄

**Pull request closed without merging**
