### PR TITLE
OWWidget: Store control area visibility as setting

### PR DESCRIPTION
**Pull request by janezd**
##### Issue

Widgets store their geometry but not the visibility of `controlArea`.

##### Description of changes

Store the visibility as a setting.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by astaric** [comment]
I vote for making this a schema_only setting.

We have also discussed storing which widgets are shown and re-displaying them once the workflow is opened. That might be related.

@ales-erjavec had a nice idea about adding save_state method to the widget and calling it whenever widget's settings are packed. With it, the setting value could be updated just before widget's settings are packed.

**Comment by janezd** [comment]
> I vote for making this a schema_only setting.

Of course. Done.

**Comment by BlazZupan** [comment]
Works as intended according to my tests.

It exposes though some other problem we have when working with sizes of the widgets. Example: put some data in Scatterplot, then hide the control, save the workflow and close. Open the workflow, show Scatterplot. The control is hidden by the widget is higher than when used in the original workflow. Add another Scatterplot: in this one, the control is shown (right, because it is a new widget), but the size of the main area is minimal (and we need to widen the widget).

A solution to above is that we would need to remember the "size" of the main area. When we expand the control, the widget should widen such that the main area remains of the same width. And when we collapse the control area, the widget should shrink to the left to maintain the width of the main area. An exception is a height of the widget: when control is shown, the hight is the max of the current height and the high with controls. When control area is collapsed, the widget should remember what was the last collapsed height and should not only reduce the width.

**Comment by janezd** [comment]
> And when we collapse the control area, the widget should shrink to the left to maintain the width of the main area.

I think it has to shrinking to the right, that is retain the position of the main area.

**Comment by janezd** [comment]
Should work now.

**Pull request merged**
