### PR TITLE
Move preprocess widget helpers into utils

### PR DESCRIPTION
**Pull request by markotoplak**

### CODE REVIEW

**Comment by PrimozGodec** [comment]
May you also write some unit test for it?

**Comment by janezd** [comment]
@markotoplak, @ales-erjavec, this PR seems harmless to merge, but I wonder whether these classes are not perhaps more general? Do they really belong `Orange.widgets.data.utils.preprocess` or could they be in something like `Orange.widgets.utils`, after perhaps some renaming?

**Comment by ales-erjavec** [comment]
The StandardItemModel, Controler and SequenceFlow are (or could be made) more general.

The current patch does not move the `PreprocessAction` class defined in owpreprocess which is used by Controller class in `createWidgetFor` (that is one of the places that should be fixed, if it is to be used more generally).

**Comment by janezd** [comment]
@markotoplak, would you move these classes to `Orange.widgets.utils`, together with the classes suggested by @ales-erjavec? If not, we can merge this PR as it is, and make them more general when we need it.

**Comment by janezd** [comment]
@markotoplak, have we decided whether we want to generalize this or keep it as it is? In any case, can you rebase, please?

**Pull request merged**
