### PR TITLE
Remove TupleList

### PR DESCRIPTION
**Pull request by PrimozGodec**
##### Issue

Test started to warn that TupleList should be removed in version >=3.27

##### Description of changes
TupleList removed

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by lanzagar** [comment]
This breaks loading pickled data saved in latest Orange (3.26).
We probably need to add the TupleList class back (so that it can be unpickled), but can keep using tuples directly in the rest of the code (as we currently are, after this PR).

We can discuss further before action, this is just a note that this needs to be handled carefully!

**Comment by janezd** [comment]
Could we have somethine like `TupleList = tuple  # backward compatibility`, so unpickle would work, but the class would be no more?

**Comment by lanzagar** [comment]
Seems better to me (and works fine as far as I can tell).

Sidenote (@PrimozGodec ): similar care probably needs to be taken when removing the ordered attribute - I now get a Read Warning in the File widget when opening a pickled dataset that says "ordered is deprecated..."

**Comment by PrimozGodec** [comment]
@lanzagar it is commented in the pull request which will warn to remove ordered and now also newly introduced test in https://github.com/biolab/orange3/pull/4879 will fail if someone removes ordered.

**Pull request merged**
