### PR TITLE
OWFile: Fix Reload for local files

### PR DESCRIPTION
**Pull request by kernc**
Fixes [issue 177](https://docs.google.com/spreadsheets/d/1spQ3zuXUEvoD-hpYEm33-lyS3OzV6cjhE7YlFlBoOw8/edit#gid=0).

@ales-erjavec can you confirm this has no negative consequences?

### CODE REVIEW

**Comment by ales-erjavec** [comment]
I cannot replicate the error. Can you describe the problem in more detail?

**Comment by kernc** [comment]
I could replicate it by saving some random /tmp/test.csv, saving, exiting. Then on restart, clicking Reload produced the said error.

**Comment by ales-erjavec** [comment]
Ah, ok I see. The fix should be on line 264 (as you mentioned in the commit message).
Note that not only can `relpath` be None, it can also be a nested path (i.e. "/" joined components), while the file_combo.currentText() will only contain the last component (basename).

**Comment by kernc** [comment]
Why does `relpath` get to be `None` in the first place? Doesn't _every_ absolute path have a (at least one) prefix and (likewise) a relative path?

**Comment by ales-erjavec** [comment]
The `prefix` and `relpath` when not None record where the path is located relative to some specific location (e.g. the location of the workflow .ows file).

Note that `prefix` is not stored as a actual path but a name identifying that special location (`'basedir'`, `'sample-datasets'`, ...)

An example. Take the following directory structure
```
$HOME/work/
    workflow.ows
    datasets/
        dataset1.tab
        dataset2.tab
```
A path within `$HOME/work/` is recorded as 

```RecentPath("$HOME/work/dataset/dataset1.tab", prefix="basedir", relpath="datasets/dataset1.tab")```

while a path outside should be

```RecentPath("$HOME/Documents/someotherdataset.tab", prefix=None, relpath=None)```

**Comment by kernc** [comment]
So if I understand it correctly, a dir structure like
```
$HOME/work/
    workflows/
        scheme1.ows
        scheme2.ows
        scheme3.ows
    datasets/
        dataset1.tab
        dataset2.tab
        dataset3.tab
```
would not resolve datasets upon relocation of `work/` since they are not within `'basedir'` (`$HOME/work/workflows/`) prefix. Is that correct?

**Comment by ales-erjavec** [comment]
Yes.

**Pull request merged**
