### PR TITLE
[WIP] owdistributions: probabilities

### PR DESCRIPTION
**Pull request by markotoplak**

### CODE REVIEW

**Comment by lanzagar** [comment]
The second commit (from Janez) changes the symbol to "x" for probabilities and then the third commit ignores it and changes it back to "o"...
Intentional? -> remove second commit
Or not? -> fix

**Comment by janezd** [comment]
@lanzagar I added confidence intervals, and "o" looks better. Consider this WIP. Right now I'm trying some other changes.

**Comment by lanzagar** [comment]
OK.
If you are changing things - I was saving this for a discussion tomorrow, but I definitely do not like (probability) confidence intervals that extend below 0...
And maybe the whole idea of having confidence intervals (and probabilities?) is unnecessarily complicating the widget?

**Comment by janezd** [comment]
Probabilities are useful. We can discuss confidence intervals, though. :)

**Pull request merged**
