### PR TITLE
Palettes: replace palettes that end with white

### LINKED ISSUE #4438: Colour palettes not ending with white
Some of the new colour palettes end in white (after yellow). When this is used in a heatmap and Colour High is changed the heatmaps looks like it has holes (e.g. white in the palette is the same as the background). Could white be changes to very pale yellow?
heatmap_palete

### PR DESCRIPTION
**Pull request by janezd**
##### Issue

Fixes #4438.

##### Description of changes

Blue - Green - Yellow: linear_bgyw_15_100_c68  is replaced with linear_bgy_10_95_c74.
Fire: linear_kryw_0_100_c71 is replaced with linear_kry_0_97_c73

Color-blind palettes do not end with white and are kept as they are.

B-G-Y was also the default palette so we may have some problems with saved settings, but IMHO there were no releases of Orange with new palettes so the problem will only appear in workflows saved from master. 

##### Includes
- [X] Code changes

### CODE REVIEW

**Comment by markotoplak** [comment]
I'd prefer not modifying colorcet palettes. The palette we call blue-green-yellow is actually blue-green-yellow-white in colorcet. Why don't we rather take the bgy palette instead of the bgyw if we dislike whites.

**Comment by janezd** [comment]
@markotoplak, you're right, as usual. I replaced the two palettes that ended with white with similar cet palettes.

**Comment by ajdapretnar** [comment]
Linear protanopic apparently ends in #FCF9F3 (252,249,243), which is not strictly white, but quite close. But I guess this is not an issue, really.

**Comment by markotoplak** [comment]
Thanks, I like this PR.

I am nitpicking, I know, but the replacement "fire" could be called differently. Its colorcet name is "CET_L4" (https://colorcet.holoviz.org/user_guide/index.html)

For the blue-green-yellow, another possibility would be to use the CET_L9. It is more similar to what we have now, it just does not that white.

I am also fine if this is merged as-is.

**Comment by janezd** [comment]
I know that what we call Fire is not called Fire in cet, but I'd still call it Fire -- I wouldn't put CET_L4 in the combo.

As for bgyw palette, it doesn't end in white, but it's still very bright, barely distinguishable from the background. Try yourself -- replace the palette (colorpalettes, line 488) with:

```
[[5, 0, 172], [6, 2, 172], [6, 5, 172], [7, 8, 173], [7, 11, 173], [8, 14, 173], [8, 16, 174], [8, 18, 174], [9, 20, 174], [9, 22, 175], [10, 24, 175], [10, 26, 175], [10, 28, 176], [11, 29, 176], [11, 31, 176], [11, 32, 177], [12, 34, 177], [12, 35, 177], [12, 37, 177], [12, 38, 178], [13, 40, 178], [13, 41, 178], [13, 42, 178], [13, 44, 179], [13, 45, 179], [13, 46, 179], [13, 48, 179], [14, 49, 180], [14, 50, 180], [14, 51, 180], [14, 53, 180], [14, 54, 180], [14, 55, 180], [14, 56, 180], [14, 58, 181], [14, 59, 181], [14, 60, 181], [14, 61, 181], [14, 62, 181], [14, 64, 181], [13, 65, 181], [13, 66, 181], [13, 67, 181], [13, 68, 181], [13, 70, 181], [13, 71, 181], [13, 72, 181], [12, 73, 181], [12, 74, 181], [12, 76, 180], [12, 77, 180], [11, 78, 180], [11, 79, 180], [11, 80, 180], [10, 81, 179], [10, 83, 179], [10, 84, 179], [9, 85, 178], [9, 86, 178], [8, 87, 177], [8, 89, 177], [8, 90, 176], [7, 91, 175], [7, 92, 174], [6, 94, 174], [6, 95, 173], [6, 96, 172], [6, 97, 170], [6, 99, 169], [7, 100, 168], [8, 101, 167], [10, 102, 165], [12, 103, 164], [13, 104, 163], [15, 106, 161], [17, 107, 160], [19, 108, 158], [20, 109, 156], [22, 110, 155], [24, 111, 153], [25, 113, 152], [27, 114, 150], [29, 115, 148], [30, 116, 146], [31, 117, 145], [33, 118, 143], [34, 119, 141], [35, 120, 139], [36, 121, 137], [37, 122, 135], [38, 124, 133], [39, 125, 131], [40, 126, 129], [41, 127, 127], [42, 128, 125], [43, 129, 123], [44, 130, 121], [44, 131, 119], [45, 132, 117], [46, 133, 114], [46, 134, 112], [46, 135, 110], [47, 137, 108], [47, 138, 105], [48, 139, 103], [48, 140, 100], [48, 141, 98], [48, 142, 96], [48, 143, 93], [49, 144, 91], [49, 145, 89], [49, 146, 86], [50, 147, 84], [50, 148, 82], [51, 149, 80], [52, 150, 78], [52, 151, 76], [53, 152, 74], [54, 153, 72], [55, 154, 71], [56, 155, 69], [57, 156, 67], [58, 157, 65], [59, 157, 64], [60, 158, 62], [61, 159, 60], [62, 160, 59], [64, 161, 57], [65, 162, 55], [66, 163, 54], [68, 164, 52], [69, 164, 51], [71, 165, 49], [72, 166, 48], [74, 167, 46], [76, 168, 45], [77, 168, 44], [79, 169, 42], [81, 170, 41], [82, 171, 39], [84, 172, 38], [86, 172, 36], [88, 173, 35], [89, 174, 34], [91, 175, 32], [93, 175, 31], [95, 176, 30], [97, 177, 28], [99, 178, 27], [101, 178, 26], [103, 179, 24], [105, 180, 23], [107, 180, 22], [109, 181, 20], [111, 182, 19], [113, 182, 18], [115, 183, 16], [117, 184, 15], [119, 184, 14], [121, 185, 12], [123, 186, 11], [125, 186, 10], [127, 187, 8], [130, 188, 7], [132, 188, 6], [134, 189, 6], [136, 190, 5], [138, 190, 4], [140, 191, 4], [143, 191, 3], [145, 192, 3], [147, 192, 3], [149, 193, 2], [152, 194, 2], [154, 194, 2], [156, 195, 2], [158, 195, 2], [160, 196, 3], [162, 196, 3], [165, 197, 3], [167, 198, 3], [169, 198, 3], [171, 199, 4], [173, 199, 4], [175, 200, 4], [177, 200, 5], [179, 201, 5], [181, 202, 6], [183, 202, 6], [185, 203, 7], [187, 203, 8], [189, 204, 9], [191, 204, 10], [193, 205, 11], [194, 206, 12], [196, 206, 13], [198, 207, 14], [200, 207, 15], [202, 208, 16], [204, 209, 17], [205, 209, 18], [207, 210, 19], [209, 210, 20], [211, 211, 21], [212, 212, 23], [214, 212, 24], [216, 213, 25], [217, 214, 26], [219, 214, 28], [221, 215, 29], [222, 215, 30], [224, 216, 32], [225, 217, 33], [227, 218, 34], [228, 218, 36], [230, 219, 37], [231, 220, 39], [233, 220, 40], [234, 221, 42], [235, 222, 44], [236, 223, 45], [238, 223, 47], [239, 224, 49], [240, 225, 51], [241, 226, 52], [242, 227, 54], [243, 227, 56], [243, 228, 59], [244, 229, 61], [245, 230, 63], [245, 231, 66], [246, 232, 69], [246, 233, 72], [247, 234, 75], [248, 235, 79], [248, 236, 83], [249, 237, 88], [250, 237, 93], [250, 238, 98], [251, 239, 103], [252, 240, 109], [252, 241, 115], [253, 241, 121], [253, 242, 128], [254, 243, 135], [254, 243, 142], [255, 244, 150], [255, 245, 159], [255, 245, 168], [255, 246, 177], [255, 247, 187], [255, 247, 198], [254, 248, 210], [253, 248, 222], [251, 249, 235], [249, 249, 249]]
```

**Comment by borondics** [comment]
One question: Did you check if the new colormap remains perceptually uniform (https://bids.github.io/colormap/)? The original colorcet colormaps are...

**Comment by janezd** [comment]
These are still colorcet palettes. I didn't modify them, I just took different palettes -- those proposed by @markotoplak.

**Pull request merged**
