### PR TITLE
Add a keyboard shortcut to delete a widget with "backspace"

### PR DESCRIPTION
**Pull request by borondics**
CMD-backspace on Mac is a bit awkward to use

### CODE REVIEW

**Comment by markotoplak** [comment]
I support this. I think Backspace is not used anywhere on canvas so it should be free. 

@BlazZupan , @janezd ?

**Comment by astaric** [comment]
+1

**Comment by kernc** [comment]
Does Backspace delete selected files in Finder?

**Comment by lanzagar** [comment]
OK, with me. Maybe even make backspace default on all platforms and remove the reversing that follows these shortcut definitions.

**Comment by borondics** [comment]
@kernc no, it doesn't, the default there is cmd-backspace.

**Pull request merged**
