### PR TITLE
Replicable sampling in Test & Score

### PR DESCRIPTION
**Pull request by MaxGreil**
##### Issue
Issue #2035 
The Test & Score widget should also have a Replicable checkbox similar to the Data Sampler widget.

##### Description of changes
Added an option to choose replicable sampling in Test & Score widget.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Partially addresses #3103 and #3287. I think we are solving this issue by passing a parameter `random_seed` to the constructor with a fixed value of 0.

@markotoplak Could you please review and see what can be improved to be in line with #3287?

**Comment by markotoplak** [comment]
Thank you for your PR. 

Currently, Test&Score is replicable by default. What is your use case where you would like to have it disabled? Test & Score is already complex and we are trying to keep widgets simple.

To see how do the different random splits affect performance, you could use select rows to sample your data (sample len(data) - 1). That will reorder your data and therefore the splits will be applied differently.

**Comment by MaxGreil** [comment]
@markotoplak thank you for your comment.
Did I understand issue #2035 then incorrectly because sampling in the Test&Score widget is already replicable?

**Comment by markotoplak** [comment]
@MaxGreil, as I understand it (please correct me if I failed to notice something), your code tries to add a no-replicable option to the widget. Otherwise the random seed was already set before.

I do not know what that bug was about. Perhaps there are some things in the backend that make results non-replicable. For example, if any learner has random elements is should be made replicable too.

So for me fixing the bug should start by finding an example which does not currently replicate, write it as a test, and then fix it. Or did you already try it?

**Comment by MaxGreil** [comment]
@markotoplak since the requirements from the original issue changed, can this PR be closed?

**Pull request closed without merging**
