### PR TITLE
[NOMERGE][WIP][RFC] Use orange canvas from a standalone package.

### PR DESCRIPTION
**Pull request by ales-erjavec**
##### Issue

Ref gh-2331

Separate canvas from widgets

https://github.com/ales-erjavec/orange-canvas/

##### Description of changes

- [x] Instrument the `__main__` to use orange canvas core
- [x] Test and fix add on installation
- [x] Report is not accessible from the main window any more
- [x] Abstract the workflow model and the execution manager in the orange-canvas-core further to make it more manageable.
...

##### Includes
- [X] Code changes
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ales-erjavec** [comment]
I am -0.5 on this though.

**Comment by astaric** [comment]
@ales-erjavec, while I am not sure about the actual switch to a standalone canvas, I would not mind moving report to Orange.widgets namespace.

Should we do it in a separate PR, or does it cause too many problems?

**Comment by ales-erjavec** [comment]
A separate PR is ok. Just need to fix failing tests and find out why every test is run twice after the move.

**Comment by astaric** [comment]
@ales-erjavec, are there any more changes that could be incorporated without merging this PR?

**Comment by ales-erjavec** [comment]
No.

**Comment by ales-erjavec** [comment]
Superseded  by gh-3772

**Pull request closed without merging**
