### PR TITLE
OWClassificationTree: Fix set_data behaviour.

### PR DESCRIPTION
**Pull request by s-alexey**
This commit solves #1044 but every other learner still has the same problem.

### CODE REVIEW

**Comment by kernc** [comment]
WRT lines of code, I have no objections here, except what's stated in https://github.com/biolab/orange3/issues/1044#issuecomment-192754237. Thanks for setting a reasonable commit message title! The commit message's description is directly the opposite, however: setting new data _should_ update and send the new model; the _learner_ (unfitted model) is what doesn't change until its parameters do.

**Comment by lanzagar** [comment]
A problem appears when the user changes settings, but does not yet push Apply. The Learner is not yet updated.
Now if the input data changes, it does not update the learner anymore, so the existing learner with old settings is used, which produces very confusing (wrong) results.

This happens because there is no "auto apply" option and no callbacks on individual settings controls.

@kernc can you coordinate this, possibly in connection with #1072.

**Comment by s-alexey** [comment]
> A problem appears when the user changes settings, but does not yet push Apply. 

@lanzagar, I think it's better to only notify the user when he updates settings but doesn't press apply button. It means we should add a callback to every setting. I will add it to #1072.

**Comment by astaric** [comment]
Fixed in #1072

**Pull request closed without merging**
