### PR TITLE
Update Highcharts to 4.2.6

### LINKED ISSUE #2088: Test & Score: AUC is not computed if some class value in missing in the test set
##### Orange version
master

##### Steps to reproduce the behavior
Take iris data set, Logistic Regression, build the classifier on the whole data set and only use some instances for testing in Test&Score. Even if samples with two different class values are present in the test set, AUC is not computed.

I understand that AUC can not be computed with a test set with only a single class value, but two class values should be enough.

### LINKED ISSUE #4933: Add installing with winget section to Readme.md and homepage
Like the title.
Recently, my [pull request in winget-pkgs (Microsoft)](https://github.com/microsoft/winget-pkgs/pull/2898) has been successfully merged, which means now you can use [winget](https://github.com/microsoft/winget-cli) to install Orange on Windows.

Cmd:
## To search
```
winget search Orange
```
Output
```
C:\WINDOWS\system32>winget search Orange
Name      Id                           Version Match
---------------------------------------------------------------
Orange    UniversityofLjubljana.Orange 3.26.0
```

## To install
```
winget install Orange
```
or with id
```
winget install --id  UniversityofLjubljana.Orange
```

### LINKED ISSUE #5113: Failing to install Orange via Pip
Hi !
I tried to install Orange via the Pip method explained here : [https://github.com/biolab/orange3](url)
While proceeding with `pip install orange3` I saw these errors:
`  ERROR: Command errored out with exit status 1:
   command: ~/orange3venv/bin/python ~/orange3venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp753675oj                                                                                                                                       
       cwd: /tmp/pip-install-u9ojt7yc/orange3`
and also
`  setup.py:155: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses          
    import imp`
and also
`  Orange/classification/_simple_tree.c: In function ‘gain_ratio_c’: 
Orange/classification/_simple_tree.c:63:2: warning: implicit declaration of function ‘qsort_r’; did you mean ‘qsort’? [-Wimplicit-function-declaration]                                                                                                                                                   
     63 |  qsort_r(base, nel, size, compar, thunk)
  Orange/classification/_simple_tree.c:147:2: note: in expansion of macro ‘QSORT_R_FUNC’                                                              
    147 |  QSORT_R_FUNC(examples, size, sizeof(struct Example), (void*) &compar_attr, compar_examples);  `
and also
`  Orange/classification/_tree_scorers.c: In function ‘__pyx_pf_6Orange_14classification_13_tree_scorers_2find_threshold_entropy’:                     
  Orange/classification/_tree_scorers.c:3115:27: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]                                                                                                                                              
   3115 |   __pyx_t_7 = ((__pyx_v_N <= __pyx_v_min_leaf) != 0); `
and also
`  Orange/classification/_tree_scorers.c: In function ‘__Pyx_modinit_type_init_code’:                                                                  
  Orange/classification/_tree_scorers.c:24988:25: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’                     
  24988 |   __pyx_type___pyx_array.tp_print = 0;`
and also
`  Orange/classification/_tree_scorers.c: In function ‘__Pyx_ParseOptionalKeywords’:                                                                   
  Orange/classification/_tree_scorers.c:25695:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]                     
  25695 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :`
And many more, then finally:
`ERROR: Could not build wheels for orange3 which use PEP 517 and cannot be installed directly
`
As I imagined, the result doesn't work:
`~/orange3venv/bin/python: Error while finding module specification for 'Orange.canvas' (ModuleNotFoundError: No module named 'Orange')
`

My system : 5.9.11-arch2-1
Python version 3.9.0 
Pip version 20.3.1

### LINKED ISSUE #5158: I could not open Orange!
- [ ] **What's wrong?**
I installed Orange3, and it was working very well but then when I try to open it again, I could not. It opens for a few seconds then it closes immediately. I re-downloaded it twice, but I had the same issue. 

Screen Shot 2021-01-05 at 8 17 07 AM
 

- Operating system: macOS Catalina, version 10.15
- Orange version: 3.27
- How you installed Orange: from the website

### PR DESCRIPTION
**Pull request by PrimozGodec**
This pull request updates version of Highcharts to 4.2.5 what is required to implement contour graph in Educational add-on's Polynomial Regression. Changes does not affect any features (just added some new features and bug fix).

Changes in Highcahrts:

- Added new option, exporting.printMaxWidth, to prevent printed charts cut off on the right side. 
- Added new option, title.widthAdjust and subtitle.widthAdjust, to prevent titles from flowing over elements.
- Added support for JPEG in offline download module
- Added support for polar columnrange series.
- Added e.originalEvent to drilldown event in order to catch modifier keys and other properties.
- Added new drilldown event, chart.events.drillupall, that is triggered after multiple single drillup events. 
- Added new option, chart.options3d.fitToPlot to fit 3D charts into the available plotting area. This may affect the layout of existing 3D charts if the layout was adjusted by chart.margin. The chart.margin setting can now normally be removed. 
- Added new option, lang.shortWeekdays, to specify short weekdays other than the first three letters of the weekday.
- Added new value, day, for pointIntervalUnit.
- Added option, legend.navigation.enabled, to allow disabling legend scroll.
- Added crisp correction for crisper treemap points.
- Added support for animating graphs to the right when updating data or setting axis extremes.
- Refactored sideways animation logic for graphs to better reflect shifting data.
- Bug fix

### CODE REVIEW

**Comment by kernc** [comment]
I believe the update obsoletes a paragraph in the _README.updating_ file. @PrimozGodec, can you check.

**Comment by kernc** [comment]
v4.2.5 is exhibiting highcharts bug 5323. Can we wait for the next point release?

**Comment by PrimozGodec** [comment]
We can wait.

**Comment by PrimozGodec** [comment]
@kernc I updated Highcharts to version 4.2.6 it seems that bug 5323 is fixed in this version. May you check if everything works fine in this widget. 

For widgets I tested it works fine.

**Pull request merged**
