### PR TITLE
modified tutorials workfolw  issue #1086

### PR DESCRIPTION
**Pull request by shark-S**
updated tutorials workflow and in issue #1086  now tutorials open with there indeed data.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
@shark-S Tutorials still open with a blank File widget.

**Comment by shark-S** [comment]
@ajdapretnar  i will be improve it but today i am participating in a hackathon and it will end on sunday so i will fix it after that.
 Sorry for  inconvenience.

**Comment by shark-S** [comment]
@ajdapretnar  when i installed orange on new system then same error coming thanks for notify i will try to improve it.

**Comment by shark-S** [comment]
@ajdapretnar  check it once more .

**Comment by ajdapretnar** [comment]
@shark-S For me tutorials still don't open with the intended data set.

**Comment by shark-S** [comment]
@ajdapretnar if once you fill tutorials's data and save them and replace them by current tutorials *.ows then i can work fine always. Please try it once again. Otherwise give me hint so i can proceed further.

**Comment by astaric** [comment]
Bug causing the issue was fixed in #1163. Tutorial workflows that has incorrect/missing datasets were updated in #1169.

**Pull request closed without merging**
