### PR TITLE
__main__: Update Orange in-app

### PR DESCRIPTION
**Pull request by irgolic**
##### Issue
As Orange can be updated from the Add-ons dialogue, there seems to be no need to redownload the whole package.

##### Description of changes
On clicking 'Yes' in the update request notification, the Installer (previously Add-ons) dialogue will open, and select Orange3 to be updated. All the user must do is press Ok.

If the user does not have install permissions, the website is opened to prompt a download.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by irgolic** [comment]
This needs to be tested with Anaconda Navigator, making sure it doesn't break anything by breaking dependencies.

**Comment by borondics** [comment]
I think this is a great addition. In the same time might be confusing to users. What happens if they update the orange3 toolbox from inside Orange and then get a message to update Orange (that would involve orange-canvas-core and orange-widget-base)?

Could there be a general solution to update all sub-packages from within Orange to be more user friendly (also not needing to uninstall/reinstall Orange on Windows for example)?

**Comment by irgolic** [comment]
> I think this is a great addition. In the same time might be confusing to users. What happens if they update the orange3 toolbox from inside Orange and then get a message to update Orange (that would involve orange-canvas-core and orange-widget-base)?

I don't quite understand. If Orange is updated, so are orange-widget-base and orange-canvas-core. Is this related to the bug you described in #5078?

> Could there be a general solution to update all sub-packages from within Orange to be more user friendly (also not needing to uninstall/reinstall Orange on Windows for example)?

How would you envision such a solution? Would an 'Upgrade All' button on the Add-ons installer dialogue, which would be equivalent to clicking on the checkboxes of all installed Add-ons, suffice?

**Comment by markotoplak** [comment]
Before merging this PR we need to test at least the following scenarios. 

- [ ] Install our Windows Conda package and try to update Orange through the add-on dialog. 
  - Try with 3.26.0 and 3.27.0.
  - Verify that the version was updated.
  - Make sure that the pip fallback was NOT used (`conda list` should not show any pypi packages).

- [ ] Install fresh Anaconda, enable conda-forge, install orange3 3.27.0 (not the latest!) from conda-forge.
  - Verify that the version was updated.
  - Make sure that the pip fallback was NOT used. 

- [ ] Install fresh Anaconda, DO NOT enable conda-forge, and install Orange from the Navigator.
  - Use the add-on dialog to update Orange.
  - Confirm that the selected version was installed and that the pip fallback was NOT used. 

The last test will likely fail.

**Comment by thocevar** [comment]
- [❌] Updating Orange from 3.26.0 using the add-on dialog fails on Win 10 if I don't run Orange as Administrator. Some packages upgrade successfully, but it chokes on openTSNE. If I run Orange as admin, upgrade succeeds and the upgraded packages come from conda-forge.

>  Attempting uninstall: openTSNE
>     Found existing installation: openTSNE 0.3.11
>     Uninstalling openTSNE-0.3.11:
>       Successfully uninstalled openTSNE-0.3.11
> ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\users\\thocevar\\appdata\\local\\orange\\lib\\site-packages\\~pentsne\\quad_tree.cp37-win_amd64.pyd'
> Consider using the `--user` option or check the permissions.

- [❌] Installing Orange using conda (from the conda-forge channel) and updating it via add-on dialog also reports an "access denied" error but then installs version 3.27.1 from pypi.

>   Attempting uninstall: Orange3
>     Found existing installation: Orange3 3.27.0
>     Uninstalling Orange3-3.27.0:
>       Successfully uninstalled Orange3-3.27.0
> ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\thocevar\\miniconda3\\Lib\\site-packages\\~range\\classification\\_simple_tree.cp38-win_amd64.pyd'
> Consider using the `--user` option or check the permissions.

I didn't try all combinations but it's not looking good.

**Comment by irgolic** [comment]
(note, all of this is already possible in the released version, this PR just directs people to it via a notif)

**Comment by ajdapretnar** [comment]
I have tried updating Orange in-app on lab Win machines. Try are at 3.23.1. Installing failed both with regular run and run as admin. Error log below:
```
Collecting Orange3<4.0a,>=3.20 (from -c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/99/52/e1fca3329c5463cc3cddb42ba95855ba20bd315a8afc25fdf6dab67c2597/Orange3-3.27.1-cp36-none-win_amd64.whl (2.6MB)
Requirement already satisfied, skipping upgrade: docutils in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (0.15.2)
Collecting openpyxl (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d4/c5/1a5f82b3020bfb27f21b302f96c8ae6a34475070015d1b1e0b197a97e2af/openpyxl-3.0.6-py2.py3-none-any.whl (242kB)
Collecting baycomp>=1.0.2 (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/05/69/3029fe9fe13e4ec14d9d6be695ee197e4cd75221c7f77eb95ac5604035b4/baycomp-1.0.2-py3-none-any.whl
Requirement already satisfied, skipping upgrade: keyrings.alt in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (3.1.1)
Collecting PyQt5!=5.15.1,>=5.12 (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/aa/72/754c693db0e745b9fe47debc3ec52844461f090d5beff28489a0cde5ef82/PyQt5-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-none-win_amd64.whl (56.9MB)
Requirement already satisfied, skipping upgrade: scipy>=0.16.1 in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (1.2.1)
Requirement already satisfied, skipping upgrade: numpy>=1.16.0 in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (1.16.4)
Collecting pyqtgraph>=0.11.0 (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/7c/8e/0cdd8613548f138ec0ffb38b00f91da69a810f322ee1d08304d37354f8d0/pyqtgraph-0.11.1-py2.py3-none-any.whl (824kB)
Requirement already satisfied, skipping upgrade: python-louvain>=0.13 in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (0.13)
Collecting AnyQt>=0.0.11 (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/0e/e9/bde5c1e6871068ff78b2ea18bd2e9bfa7cd6ecfd1e8f1c280cb238138bc1/AnyQt-0.0.11-py2.py3-none-any.whl (46kB)
Collecting PyQtWebEngine>=5.12 (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/67/84/afcf3a4e2b090c52cc81f3083eed21832ea1ecb47649f7783105328b00a4/PyQtWebEngine-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-none-win_amd64.whl (60.2MB)
Collecting scikit-learn!=0.23.0,>=0.22.0 (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/3c/d3/63700971e89bc5024d4356310229f5cdc93927c8c8bf95c53bb7b5e4a62e/scikit_learn-0.24.1-cp36-cp36m-win_amd64.whl (6.8MB)
Requirement already satisfied, skipping upgrade: xlsxwriter in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (1.1.8)
Collecting orange-canvas-core<0.2a,>=0.1.18 (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/50/6d/034cf6e8c4773178af5b1727315602358a4767835e31ce8839268b42467c/orange_canvas_core-0.1.18-py3-none-any.whl (456kB)
Collecting orange-widget-base>=4.8.1 (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/46/82/60bf4132145aa1ed53e9fe9e1ea87927efdbc0b340967cd44f9f126776b7/orange_widget_base-4.10.0-py3-none-any.whl (231kB)
Requirement already satisfied, skipping upgrade: requests in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (2.22.0)
Collecting httpx~=0.14.0 (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/bb/f9/e187987c0f7e22c92953f2e33d5a68df545719cf6798a1f08340db5fcac1/httpx-0.14.3-py3-none-any.whl (62kB)
Requirement already satisfied, skipping upgrade: bottleneck>=1.0.0 in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (1.2.1)
Requirement already satisfied, skipping upgrade: joblib>=0.9.4 in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (0.13.2)
Requirement already satisfied, skipping upgrade: pyyaml in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (5.1.2)
Requirement already satisfied, skipping upgrade: chardet>=3.0.2 in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (3.0.4)
Requirement already satisfied, skipping upgrade: matplotlib>=2.0.0 in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (3.1.1)
Requirement already satisfied, skipping upgrade: xlrd>=0.9.2 in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (1.2.0)
Requirement already satisfied, skipping upgrade: keyring in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (18.0.0)
Requirement already satisfied, skipping upgrade: networkx in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (2.3)
Collecting openTSNE>=0.4.3 (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/b7/cc/ad49da14fe47fa28009fd4158e45b89111e65251e30088c0064c0f35e9dd/openTSNE-0.5.1-cp36-cp36m-win_amd64.whl (393kB)
Requirement already satisfied, skipping upgrade: serverfiles in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (0.3.0)
Requirement already satisfied, skipping upgrade: pandas in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (0.25.1)
Requirement already satisfied, skipping upgrade: setuptools>=36.3 in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (41.0.1)
Requirement already satisfied, skipping upgrade: pip>=9.0 in c:\users\biolab\appdata\local\orange\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (19.2.2)
Collecting jdcal (from openpyxl->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/f0/da/572cbc0bc582390480bbd7c4e93d14dc46079778ed915b505dc494b37c57/jdcal-1.4.1-py2.py3-none-any.whl
Collecting et-xmlfile (from openpyxl->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/22/28/a99c42aea746e18382ad9fb36f64c1c1f04216f41797f2f0fa567da11388/et_xmlfile-1.0.1.tar.gz
Requirement already satisfied, skipping upgrade: six in c:\users\biolab\appdata\local\orange\lib\site-packages (from keyrings.alt->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (1.12.0)
Collecting PyQt5-sip<13,>=12.8 (from PyQt5!=5.15.1,>=5.12->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/59/0e/f51483e98c407687ec6e99d21ec1333c42a4d285933f2863494676d22896/PyQt5_sip-12.8.1-cp36-cp36m-win_amd64.whl (62kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn!=0.23.0,>=0.22.0->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/f7/12/ec3f2e203afa394a149911729357aa48affc59c20e2c1c8297a60f33f133/threadpoolctl-2.1.0-py3-none-any.whl
Requirement already satisfied, skipping upgrade: commonmark>=0.8.1 in c:\users\biolab\appdata\local\orange\lib\site-packages (from orange-canvas-core<0.2a,>=0.1.18->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (0.8.1)
Requirement already satisfied, skipping upgrade: cachecontrol[filecache] in c:\users\biolab\appdata\local\orange\lib\site-packages (from orange-canvas-core<0.2a,>=0.1.18->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (0.12.5)
Collecting dictdiffer (from orange-canvas-core<0.2a,>=0.1.18->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/97/92/350b6b6ec39c5f87d98d04c91a50c498518716a05368e6dea88b5c69b590/dictdiffer-0.8.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\users\biolab\appdata\local\orange\lib\site-packages (from requests->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (2.8)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\biolab\appdata\local\orange\lib\site-packages (from requests->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (1.24.2)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\biolab\appdata\local\orange\lib\site-packages (from requests->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (2019.6.16)
Requirement already satisfied, skipping upgrade: rfc3986[idna2008]<2,>=1.3 in c:\users\biolab\appdata\local\orange\lib\site-packages (from httpx~=0.14.0->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (1.3.2)
Collecting httpcore==0.10.* (from httpx~=0.14.0->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/48/20/eb122c9a73251caa7a0a5c60ccc0707843e917aabc65ed34162a54fee147/httpcore-0.10.2-py3-none-any.whl (48kB)
Collecting sniffio (from httpx~=0.14.0->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/52/b0/7b2e028b63d092804b6794595871f936aafa5e9322dcaaad50ebf67445b3/sniffio-1.2.0-py3-none-any.whl
Requirement already satisfied, skipping upgrade: cycler>=0.10 in c:\users\biolab\appdata\local\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (0.10.0)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in c:\users\biolab\appdata\local\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (1.1.0)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\biolab\appdata\local\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (2.4.2)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in c:\users\biolab\appdata\local\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (2.8.0)
Requirement already satisfied, skipping upgrade: pywin32; sys_platform == "win32" in c:\users\biolab\appdata\local\orange\lib\site-packages (from keyring->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (223)
Requirement already satisfied, skipping upgrade: entrypoints in c:\users\biolab\appdata\local\orange\lib\site-packages (from keyring->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (0.3)
Requirement already satisfied, skipping upgrade: decorator>=4.3.0 in c:\users\biolab\appdata\local\orange\lib\site-packages (from networkx->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (4.4.0)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in c:\users\biolab\appdata\local\orange\lib\site-packages (from pandas->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (2019.2)
Requirement already satisfied, skipping upgrade: future in c:\users\biolab\appdata\local\orange\lib\site-packages (from commonmark>=0.8.1->orange-canvas-core<0.2a,>=0.1.18->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (0.17.1)
Requirement already satisfied, skipping upgrade: msgpack in c:\users\biolab\appdata\local\orange\lib\site-packages (from cachecontrol[filecache]->orange-canvas-core<0.2a,>=0.1.18->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (0.6.1)
Requirement already satisfied, skipping upgrade: lockfile>=0.9 in c:\users\biolab\appdata\local\orange\lib\site-packages (from cachecontrol[filecache]->orange-canvas-core<0.2a,>=0.1.18->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1)) (0.12.2)
Collecting h11<0.10,>=0.8 (from httpcore==0.10.*->httpx~=0.14.0->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/5a/fd/3dad730b0f95e78aeeb742f96fa7bbecbdd56a58e405d3da440d5bfb90c6/h11-0.9.0-py2.py3-none-any.whl (53kB)
Collecting contextvars>=2.1; python_version < "3.7" (from sniffio->httpx~=0.14.0->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/83/96/55b82d9f13763be9d672622e1b8106c85acb83edd7cc2fa5bc67cd9877e9/contextvars-2.4.tar.gz
Collecting immutables>=0.9 (from contextvars>=2.1; python_version < "3.7"->sniffio->httpx~=0.14.0->Orange3<4.0a,>=3.20->-c C:\Users\biolab\AppData\Local\Temp\tmp3y7o8k8j.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cc/20/e86be7e828a12a0d8895fff21c71bb932521c1ffc5528d32a58d90541cbd/immutables-0.14-cp36-cp36m-win_amd64.whl (54kB)
Building wheels for collected packages: et-xmlfile, contextvars
  Building wheel for et-xmlfile (setup.py): started
  Building wheel for et-xmlfile (setup.py): finished with status 'done'
  Created wheel for et-xmlfile: filename=et_xmlfile-1.0.1-cp36-none-any.whl size=8920 sha256=ce45a9d666f757e785f1e76a0ae4f59defd59197c5696bb6739de5cc63d2d34e
  Stored in directory: C:\Users\biolab\AppData\Local\pip\Cache\wheels\2a\77\35\0da0965a057698121fc7d8c5a7a9955cdbfb3cc4e2423cad39
  Building wheel for contextvars (setup.py): started
  Building wheel for contextvars (setup.py): finished with status 'done'
  Created wheel for contextvars: filename=contextvars-2.4-cp36-none-any.whl size=7671 sha256=df3d23f275f3b61e27925b04a458051b301f54c502434464b5eacebfeb7a9cdc
  Stored in directory: C:\Users\biolab\AppData\Local\pip\Cache\wheels\a5\7d\68\1ebae2668bda2228686e3c1cf16f2c2384cea6e9334ad5f6de
Successfully built et-xmlfile contextvars
ERROR: opentsne 0.5.1 has requirement numpy>=1.16.6, but you'll have numpy 1.16.4 which is incompatible.
Installing collected packages: jdcal, et-xmlfile, openpyxl, baycomp, PyQt5-sip, PyQt5, pyqtgraph, AnyQt, PyQtWebEngine, threadpoolctl, scikit-learn, dictdiffer, orange-canvas-core, orange-widget-base, immutables, contextvars, sniffio, h11, httpcore, httpx, openTSNE, Orange3
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\biolab\\AppData\\Local\\Orange\\Lib\\site-packages\\PyQt5\\QtCore.pyd'
Consider using the `--user` option or check the permissions.
```

**Comment by markotoplak** [comment]
Here is a user that had problems with updating through the add-on dialog #5693.

**Comment by markotoplak** [comment]
Closing for now because it needs work on add-on infrastructure. Continue discussion on biolab/orange-canvas-core#213.

**Pull request closed without merging**
